# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCartPropertyRemindersItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      after_hours: :after_hours
    }.freeze

    SCHEMA = {
      after_hours: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1, maximum: 72}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor :after_hours

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @after_hours = hash[:after_hours]
    end
  end
end
