# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCart < SellApp::Types::BaseModel
    HASH_ATTRS = {
      enabled: :enabled,
      min_total_cents: :min_total_cents,
      max_total_cents: :max_total_cents,
      reminders: :reminders,
      incentive_mode: :incentive_mode,
      coupon_id: :coupon_id,
      send_incentive_on_step: :send_incentive_on_step
    }.freeze

    SCHEMA = {
      enabled: {required: true, schema: {kind: :boolean}},
      min_total_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 0}}},
      max_total_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 0}}},
      reminders: {required: false, schema: {kind: :array, items: {kind: :model, name: "SellApp::ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCartPropertyRemindersItem"}, max: 3}},
      incentive_mode: {required: false, schema: {kind: :nullable, inner: {kind: :enum, values: ["none", "existing_coupon", "null"]}}},
      coupon_id: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1}}},
      send_incentive_on_step: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1, maximum: 3}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :enabled,
      :min_total_cents,
      :max_total_cents,
      :reminders,
      :incentive_mode,
      :coupon_id,
      :send_incentive_on_step

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @enabled = hash[:enabled]
      @min_total_cents = hash[:min_total_cents]
      @max_total_cents = hash[:max_total_cents]
      @reminders = hash[:reminders] ? hash[:reminders].map { |item| item ? SellApp::ReplaceMarketingSettingsRequestApplicationJsonPropertyAbandonedCartPropertyRemindersItem.new(item) : nil } : nil
      @incentive_mode = hash[:incentive_mode]
      @coupon_id = hash[:coupon_id]
      @send_incentive_on_step = hash[:send_incentive_on_step]
    end
  end
end
