# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkUpdateCashbackRuleRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      percent_basis: :percent_basis,
      maximum_cashback_cents: :maximum_cashback_cents,
      is_active: :is_active,
      product_ids: :product_ids
    }.freeze

    SCHEMA = {
      percent_basis: {required: false, schema: {kind: :integer, minimum: 1, maximum: 10000}},
      maximum_cashback_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1, maximum: 999999999999}}},
      is_active: {required: false, schema: {kind: :boolean}},
      product_ids: {required: false, schema: {kind: :array, items: {kind: :integer}, unique: true}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :percent_basis,
      :maximum_cashback_cents,
      :is_active,
      :product_ids

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @percent_basis = hash[:percent_basis]
      @maximum_cashback_cents = hash[:maximum_cashback_cents]
      @is_active = hash[:is_active]
      @product_ids = hash[:product_ids]
    end
  end
end
