# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  UpdateCashbackRuleResponseValue200ApplicationJsonPropertyData = ArchiveCashbackRuleResponseValue200ApplicationJsonPropertyData
end
