# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class DeleteVariantSerialResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      serial: :serial,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :string}},
      serial: {required: true, schema: {kind: :string, max: 2048}},
      created_at: {required: true, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: true, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :serial,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @serial = hash[:serial]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
