# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkAppendVariantSerialInventoryRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      serials: :serials,
      remove_duplicates: :remove_duplicates
    }.freeze

    SCHEMA = {
      serials: {required: true, schema: {kind: :array, items: {kind: :string, max: 2048}, min: 1, max: 5000}},
      remove_duplicates: {required: false, schema: {kind: :boolean}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :serials,
      :remove_duplicates

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @serials = hash[:serials]
      @remove_duplicates = hash[:remove_duplicates]
    end
  end
end
