# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ListIntegrationEventsResponseValue200ApplicationJsonPropertyMeta < SellApp::Types::BaseModel
    HASH_ATTRS = {
      next_cursor: :next_cursor,
      has_more: :has_more,
      retention_days: :retention_days
    }.freeze

    SCHEMA = {
      next_cursor: {required: true, schema: {kind: :string}},
      has_more: {required: true, schema: {kind: :boolean}},
      retention_days: {required: true, schema: {kind: :literal, value: 30}}
    }.freeze
    ADDITIONAL_PROPERTIES = false
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :next_cursor,
      :has_more,
      :retention_days

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @next_cursor = hash[:next_cursor]
      @has_more = hash[:has_more]
      @retention_days = hash[:retention_days]
    end
  end
end
