# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListOrderEventsResponseValue200ApplicationJsonPropertyDataItemPropertyData = CancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata
end
