# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkListOrderEventsResponseValue200ApplicationJson = SdkListIntegrationEventsResponseValue200ApplicationJson
end
