# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      stock: :stock,
      serials: :serials,
      removeDuplicate: :remove_duplicate,
      parsingMode: :parsing_mode,
      comment: :comment,
      webhook: :webhook,
      booking: :booking,
      credit_rate_tiers: :credit_rate_tiers
    }.freeze

    SCHEMA = {
      stock: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      serials: {required: false, schema: {kind: :array, items: {kind: :string}}},
      removeDuplicate: {required: false, schema: {kind: :boolean}},
      parsingMode: {required: false, schema: {kind: :enum, values: ["COMMA", "NEW_LINE", "SPACE", "CUSTOM"]}},
      comment: {required: false, schema: {kind: :string}},
      webhook: {required: false, schema: {kind: :string, format: "uri"}},
      booking: {required: false, schema: {kind: :model, name: "SellApp::CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking"}},
      credit_rate_tiers: {required: false, schema: {kind: :array, items: {kind: :model, name: "SellApp::CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :stock,
      :serials,
      :remove_duplicate,
      :parsing_mode,
      :comment,
      :webhook,
      :booking,
      :credit_rate_tiers

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @stock = hash[:stock]
      @serials = hash[:serials]
      @remove_duplicate = hash[:removeDuplicate]
      @parsing_mode = hash[:parsingMode]
      @comment = hash[:comment]
      @webhook = hash[:webhook]
      @booking = hash[:booking] ? SellApp::CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyBooking.new(hash[:booking]) : nil
      @credit_rate_tiers = hash[:credit_rate_tiers] ? hash[:credit_rate_tiers].map { |item| item ? SellApp::CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyDeliverablePropertyDataPropertyCreditRateTiersItem.new(item) : nil } : nil
    end
  end
end
