# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkUpdateAddOnResponseValue200ApplicationJson = SdkCreateAddOnDraftResponseValue201ApplicationJson
end
