# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  CreateUpsellOfferResponseValue201ApplicationJsonPropertyDataPropertySourceVariant = BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem
end
