# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateUpsellOfferRequestApplicationJsonPropertyItemsItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      target_listing_id: :target_listing_id,
      target_variant_id: :target_variant_id,
      headline: :headline,
      description: :description,
      discount_type: :discount_type,
      discount_value: :discount_value,
      maximum_discount_amount: :maximum_discount_amount
    }.freeze

    SCHEMA = {
      id: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      target_listing_id: {required: true, schema: {kind: :integer}},
      target_variant_id: {required: true, schema: {kind: :integer}},
      headline: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 120}}},
      description: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 255}}},
      discount_type: {required: false, schema: {kind: :nullable, inner: {kind: :enum, values: ["percentage", "fixed", "null"]}}},
      discount_value: {required: false, schema: {kind: :nullable, inner: {kind: :union, variants: [{kind: :number, maximum: 99999999.99, exclusive_minimum: 0, multiple_of: 0.01}, {kind: :string, maximum: 99999999.99, exclusive_minimum: 0, multiple_of: 0.01}]}}},
      maximum_discount_amount: {required: false, schema: {kind: :nullable, inner: {kind: :union, variants: [{kind: :number, maximum: 99999999.99, exclusive_minimum: 0, multiple_of: 0.01}, {kind: :string, maximum: 99999999.99, exclusive_minimum: 0, multiple_of: 0.01}]}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :target_listing_id,
      :target_variant_id,
      :headline,
      :description,
      :discount_type,
      :discount_value,
      :maximum_discount_amount

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @target_listing_id = hash[:target_listing_id]
      @target_variant_id = hash[:target_variant_id]
      @headline = hash[:headline]
      @description = hash[:description]
      @discount_type = hash[:discount_type]
      @discount_value = hash[:discount_value]
      @maximum_discount_amount = hash[:maximum_discount_amount]
    end
  end
end
