# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  UpdateUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertySourceProduct = BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyVariantsItem
end
