# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class DisconnectCommunityPlatformResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      platform: :platform,
      disconnected: :disconnected
    }.freeze

    SCHEMA = {
      platform: {required: true, schema: {kind: :enum, values: ["discord", "telegram", "slack", "whatsapp"]}},
      disconnected: {required: true, schema: {kind: :literal, value: true}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :platform,
      :disconnected

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @platform = hash[:platform]
      @disconnected = hash[:disconnected]
    end
  end
end
