# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ListCommunityConnectionsResponseValue200ApplicationJsonPropertyDataItemPropertyAccountsItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      username: :username,
      display_name: :display_name,
      avatar_url: :avatar_url
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :string}},
      username: {required: true, schema: {kind: :nullable, inner: {kind: :string}}},
      display_name: {required: true, schema: {kind: :nullable, inner: {kind: :string}}},
      avatar_url: {required: true, schema: {kind: :nullable, inner: {kind: :string, format: "uri"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :username,
      :display_name,
      :avatar_url

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @username = hash[:username]
      @display_name = hash[:display_name]
      @avatar_url = hash[:avatar_url]
    end
  end
end
