# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyAvailableServersItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      name: :name,
      type: :type
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :string}},
      name: {required: true, schema: {kind: :string}},
      type: {required: true, schema: {kind: :literal, value: "group"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :name,
      :type

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @name = hash[:name]
      @type = hash[:type]
    end
  end
end
