# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkSendTestWebhookResponseValue200ApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      data: :data
    }.freeze

    SCHEMA = {
      data: {required: true, schema: {kind: :model, name: "SellApp::SendTestWebhookResponseValue200ApplicationJsonPropertyData"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor :data

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @data = hash[:data] ? SellApp::SendTestWebhookResponseValue200ApplicationJsonPropertyData.new(hash[:data]) : nil
    end
  end
end
