# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkSearchWebhookChannelsRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      search: :search,
      event: :event,
      page: :page,
      limit: :limit
    }.freeze

    SCHEMA = {
      search: {required: false, schema: {kind: :model, name: "SellApp::SearchWebhookChannelsRequestApplicationJsonPropertySearch"}},
      event: {required: false, schema: {kind: :nullable, inner: {kind: :enum, values: ["booking.cancelled", "booking.rescheduled", "cash_app.payment_requires_attention", "charge.completed", "charge.created", "charge.disputed", "charge.partial_paid", "charge.review", "feedback.created", "order.completed", "order.created", "order.disputed", "order.manual_payment_completed", "order.paid", "order.partial_paid", "product.created", "product.trashed", "product.updated", "subscription.cancelled", "subscription.created", "subscription.renewed", "ticket_message.created", "variant.created", "variant.sold_out", "variant.updated"]}}},
      page: {required: false, schema: {kind: :integer, minimum: 1}},
      limit: {required: false, schema: {kind: :integer, minimum: 1, maximum: 100}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :search,
      :event,
      :page,
      :limit

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @search = hash[:search] ? SellApp::SearchWebhookChannelsRequestApplicationJsonPropertySearch.new(hash[:search]) : nil
      @event = hash[:event]
      @page = hash[:page]
      @limit = hash[:limit]
    end
  end
end
