# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyPaymentPropertySubtotal = CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee
end
