# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      invoice_id: :invoice_id,
      product_variant_id: :product_variant_id,
      deliverable: :deliverable,
      quantity: :quantity,
      additional_information: :additional_information
    }.freeze

    SCHEMA = {
      invoice_id: {required: true, schema: {kind: :integer}},
      product_variant_id: {required: true, schema: {kind: :integer}},
      deliverable: {required: true, schema: {kind: :model, name: "SellApp::GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable"}},
      quantity: {required: true, schema: {kind: :integer}},
      additional_information: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :invoice_id,
      :product_variant_id,
      :deliverable,
      :quantity,
      :additional_information

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @invoice_id = hash[:invoice_id]
      @product_variant_id = hash[:product_variant_id]
      @deliverable = hash[:deliverable] ? SellApp::GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable.new(hash[:deliverable]) : nil
      @quantity = hash[:quantity]
      @additional_information = hash[:additional_information] ? hash[:additional_information].map { |item| item ? SellApp::GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyAdditionalInformationItem.new(item) : nil } : nil
    end
  end
end
