# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  GetInvoiceResponseValue200ApplicationJsonPropertyData = CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice
end
