# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  MarkPendingInvoiceVoidedResponseValue200ApplicationJsonPropertyStatusPropertyStatus = CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus
end
