# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  MarkPendingInvoiceCompletedResponseValue200ApplicationJsonPropertyCustomerInformation = CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyCustomerInformation
end
