# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkMarkPendingInvoiceVoidedResponseValue200ApplicationJson = CreateInvoiceRefundResponseValue200ApplicationJsonPropertyDataPropertyInvoice
end
