# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  GetAppointmentResponseValue200ApplicationJsonPropertyDataPropertyVariant = CancelAppointmentResponseValue200ApplicationJsonPropertyDataPropertyProduct
end
