# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateCustomerSessionRequestApplicationJsonOneOfValue1 < SellApp::Types::BaseModel
    HASH_ATTRS = {
      customer_id: :customer_id
    }.freeze

    SCHEMA = {
      customer_id: {required: true, schema: {kind: :integer}}
    }.freeze
    ADDITIONAL_PROPERTIES = false
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor :customer_id

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @customer_id = hash[:customer_id]
    end
  end
end
