# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class DeleteVariantDeliverableFileResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      custom_name: :custom_name,
      filename: :filename,
      extension: :extension,
      mime_type: :mime_type,
      size: :size,
      watermark: :watermark,
      max_downloads: :max_downloads,
      limit_to_purchase_ip: :limit_to_purchase_ip,
      folder_id: :folder_id,
      variant_id: :variant_id,
      product_id: :product_id,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      custom_name: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 255}}},
      filename: {required: true, schema: {kind: :string}},
      extension: {required: true, schema: {kind: :string}},
      mime_type: {required: true, schema: {kind: :string}},
      size: {required: true, schema: {kind: :integer, minimum: 0}},
      watermark: {required: true, schema: {kind: :boolean}},
      max_downloads: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1}}},
      limit_to_purchase_ip: {required: true, schema: {kind: :boolean}},
      folder_id: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      variant_id: {required: true, schema: {kind: :integer}},
      product_id: {required: true, schema: {kind: :integer}},
      created_at: {required: false, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: false, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :custom_name,
      :filename,
      :extension,
      :mime_type,
      :size,
      :watermark,
      :max_downloads,
      :limit_to_purchase_ip,
      :folder_id,
      :variant_id,
      :product_id,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @custom_name = hash[:custom_name]
      @filename = hash[:filename]
      @extension = hash[:extension]
      @mime_type = hash[:mime_type]
      @size = hash[:size]
      @watermark = hash[:watermark]
      @max_downloads = hash[:max_downloads]
      @limit_to_purchase_ip = hash[:limit_to_purchase_ip]
      @folder_id = hash[:folder_id]
      @variant_id = hash[:variant_id]
      @product_id = hash[:product_id]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
