# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkUpdateVariantDeliverableFileResponseValue200ApplicationJson = SdkDeleteVariantDeliverableFileResponseValue200ApplicationJson
end
