# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetPromotionResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      name: :name,
      status: :status,
      starts_at: :starts_at,
      ends_at: :ends_at,
      priority: :priority,
      is_stackable: :is_stackable,
      max_redemptions: :max_redemptions,
      phases: :phases,
      created_at: :created_at,
      updated_at: :updated_at,
      deleted_at: :deleted_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      name: {required: true, schema: {kind: :string}},
      status: {required: true, schema: {kind: :enum, values: ["active", "disabled"]}},
      starts_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      ends_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      priority: {required: true, schema: {kind: :integer, minimum: 0}},
      is_stackable: {required: true, schema: {kind: :boolean}},
      max_redemptions: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1}}},
      phases: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::GetPromotionResponseValue200ApplicationJsonPropertyDataPropertyPhasesItem"}}},
      created_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      updated_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      deleted_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :name,
      :status,
      :starts_at,
      :ends_at,
      :priority,
      :is_stackable,
      :max_redemptions,
      :phases,
      :created_at,
      :updated_at,
      :deleted_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @name = hash[:name]
      @status = hash[:status]
      @starts_at = hash[:starts_at]
      @ends_at = hash[:ends_at]
      @priority = hash[:priority]
      @is_stackable = hash[:is_stackable]
      @max_redemptions = hash[:max_redemptions]
      @phases = hash[:phases] ? hash[:phases].map { |item| item ? SellApp::GetPromotionResponseValue200ApplicationJsonPropertyDataPropertyPhasesItem.new(item) : nil } : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @deleted_at = hash[:deleted_at]
    end
  end
end
