# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  BatchUpdateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem = BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyGroupsItem
end
