# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetTicketMessageResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      author: :author,
      sender: :sender,
      content: :content,
      created_at: :created_at,
      updated_at: :updated_at,
      ticket_id: :ticket_id
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      author: {required: true, schema: {kind: :string}},
      sender: {required: true, schema: {kind: :nullable, inner: {kind: :string}}},
      content: {required: true, schema: {kind: :string}},
      created_at: {required: true, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: true, schema: {kind: :string, format: "date-time"}},
      ticket_id: {required: true, schema: {kind: :integer}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :author,
      :sender,
      :content,
      :created_at,
      :updated_at,
      :ticket_id

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @author = hash[:author]
      @sender = hash[:sender]
      @content = hash[:content]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @ticket_id = hash[:ticket_id]
    end
  end
end
