# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetTicketResponseValue200ApplicationJsonPropertyDataPropertyCustomer < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      email: :email
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      email: {required: true, schema: {kind: :string}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :email

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @email = hash[:email]
    end
  end
end
