# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ReplaceSectionOrderResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem = BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem
end
