# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ReplaceSectionResponseValue200ApplicationJsonPropertyData = BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItem
end
