# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkV2ReplaceSectionResponseValue200ApplicationJson = SdkCreateSectionResponseValue201ApplicationJson
end
