# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkV2ReplyToTicketResponseValue201ApplicationJson = SdkGetTicketMessageResponseValue200ApplicationJson
end
