# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkV2SearchFeedbackRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      filters: :filters,
      sort: :sort,
      search: :search,
      includes: :includes
    }.freeze

    SCHEMA = {
      filters: {required: false, schema: {kind: :array, items: {kind: :model, name: "SellApp::V2SearchFeedbackRequestApplicationJsonPropertyFiltersItem"}}},
      sort: {required: false, schema: {kind: :array, items: {kind: :model, name: "SellApp::V2SearchFeedbackRequestApplicationJsonPropertySortItem"}}},
      search: {required: false, schema: {kind: :model, name: "SellApp::V2SearchFeedbackRequestApplicationJsonPropertySearch"}},
      includes: {required: false, schema: {kind: :array, items: {kind: :model, name: "SellApp::V2SearchFeedbackRequestApplicationJsonPropertyIncludesItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :filters,
      :sort,
      :search,
      :includes

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @filters = hash[:filters] ? hash[:filters].map { |item| item ? SellApp::V2SearchFeedbackRequestApplicationJsonPropertyFiltersItem.new(item) : nil } : nil
      @sort = hash[:sort] ? hash[:sort].map { |item| item ? SellApp::V2SearchFeedbackRequestApplicationJsonPropertySortItem.new(item) : nil } : nil
      @search = hash[:search] ? SellApp::V2SearchFeedbackRequestApplicationJsonPropertySearch.new(hash[:search]) : nil
      @includes = hash[:includes] ? hash[:includes].map { |item| item ? SellApp::V2SearchFeedbackRequestApplicationJsonPropertyIncludesItem.new(item) : nil } : nil
    end
  end
end
