# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem = GetFeedbackResponseValue200ApplicationJsonPropertyData
end
