# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetCustomerWalletResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      customer_id: :customer_id,
      customer_email: :customer_email,
      balance_cents: :balance_cents,
      held_cents: :held_cents,
      available_cents: :available_cents,
      status: :status,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      customer_id: {required: true, schema: {kind: :integer}},
      customer_email: {required: false, schema: {kind: :string, format: "email"}},
      balance_cents: {required: true, schema: {kind: :integer, minimum: 0}},
      held_cents: {required: false, schema: {kind: :integer, minimum: 0}},
      available_cents: {required: false, schema: {kind: :integer, minimum: 0}},
      status: {required: true, schema: {kind: :enum, values: ["active", "frozen"]}},
      created_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      updated_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :customer_id,
      :customer_email,
      :balance_cents,
      :held_cents,
      :available_cents,
      :status,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @customer_id = hash[:customer_id]
      @customer_email = hash[:customer_email]
      @balance_cents = hash[:balance_cents]
      @held_cents = hash[:held_cents]
      @available_cents = hash[:available_cents]
      @status = hash[:status]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
