# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType
      IMAGE = 'image'
      VIDEO = 'video'
      ALL = [IMAGE, VIDEO].freeze
    end
  end
end
