# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    CreateHighlightResponseValue201ApplicationJsonPropertyDataPropertyMediaItemType = AddHighlightMediaResponseValue201ApplicationJsonPropertyDataType
  end
end
