# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    CreateWalletTopUpResponseValue201ApplicationJsonPropertyDataPaymentMethod = BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPaymentMethods
  end
end
