# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class CreateExportResponseValue201ApplicationJsonPropertyDataType
      SALES = 'sales'
      TAX = 'tax'
      CUSTOMERS = 'customers'
      AFFILIATE_PAYOUTS = 'affiliate_payouts'
      ALL = [SALES, TAX, CUSTOMERS, AFFILIATE_PAYOUTS].freeze
    end
  end
end
