# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItemType
      STRING = 'string'
      ENUM = 'enum'
      BOOLEAN = 'boolean'
      ARRAY = 'array'
      DECIMAL = 'decimal'
      ALL = [STRING, ENUM, BOOLEAN, ARRAY, DECIMAL].freeze
    end
  end
end
