# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class EnableOrDisablePaymentMethodResponseValue200ApplicationJsonPropertyDataConnectionType
      OAUTH = 'oauth'
      API_KEYS = 'api_keys'
      WALLET = 'wallet'
      CUSTOM = 'custom'
      ALL = [OAUTH, API_KEYS, WALLET, CUSTOM].freeze
    end
  end
end
