# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    GetAffiliateResponseValue200ApplicationJsonPropertyDataStatus = AffiliatesStatus
  end
end
