# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class InvoicesSearchBy
      DEFAULT = 'default'
      TRANSACTION_ID = 'transaction_id'
      SERIAL_CODE = 'serial_code'
      ADDITIONAL_INFO = 'additional_info'
      PRODUCT_NAME = 'product_name'
      DISCORD_DATA = 'discord_data'
      CRYPTO_TXID = 'crypto_txid'
      CRYPTO_ADDRESS = 'crypto_address'
      COUPON_CODE = 'coupon_code'
      ALL = [DEFAULT, TRANSACTION_ID, SERIAL_CODE, ADDITIONAL_INFO, PRODUCT_NAME, DISCORD_DATA, CRYPTO_TXID, CRYPTO_ADDRESS, COUPON_CODE].freeze
    end
  end
end
