# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class ListOrderDeliverablesResponseValue200ApplicationJsonPropertyDataItemStatus
      PENDING = 'pending'
      DELIVERED = 'delivered'
      ALL = [PENDING, DELIVERED].freeze
    end
  end
end
