# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    ListWebhookDeliveriesResponseValue200ApplicationJsonPropertyDataItemStatus = GetWebhookDeliveryResponseValue200ApplicationJsonPropertyDataStatus
  end
end
