# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    ReplaceNotificationChannelResponseValue200ApplicationJsonPropertyDataType = CreateNotificationChannelResponseValue201ApplicationJsonPropertyDataType
  end
end
