# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    Response = Struct.new(:data, :status, :headers, :request_id, keyword_init: true)
  end
end
