# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    SdkReplaceCustomPaymentMethodRequestApplicationJsonType = CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyDataType
  end
end
