# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class SdkConfirmSubscriptionPlanChangeRequestApplicationJsonEffectiveTiming
      IMMEDIATE = 'immediate'
      NEXT_RENEWAL = 'next_renewal'
      ALL = [IMMEDIATE, NEXT_RENEWAL].freeze
    end
  end
end
