# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class SearchCreditsProductsRequestApplicationJsonPropertyFiltersItemField
      ID = 'id'
      VISIBILITY = 'visibility'
      IS_DRAFT = 'is_draft'
      ALL = [ID, VISIBILITY, IS_DRAFT].freeze
    end
  end
end
