# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    class SearchAddOnsRequestApplicationJsonPropertySortItemDirection
      ASC = 'asc'
      DESC = 'desc'
      ALL = [ASC, DESC].freeze
    end
  end
end
