# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    UpdateWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind = ArchiveWalletBonusTierResponseValue200ApplicationJsonPropertyDataBonusKind
  end
end
