# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    UpdateCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyQuestionsItemQuestionType = CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType
  end
end
