# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  module Types
    V2SearchFeedbackResponseValue200ApplicationJsonPropertyDataItemSentiment = V2GetFeedbackResponseValue200ApplicationJsonPropertyDataSentiment
  end
end
