# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateChargeResponseValue201ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      url: :url,
      status: :status,
      custom_payment_method_id: :custom_payment_method_id
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      url: {required: true, schema: {kind: :string}},
      status: {required: true, schema: {kind: :string}},
      custom_payment_method_id: {required: true, schema: {kind: :nullable, inner: {kind: :string}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :url,
      :status,
      :custom_payment_method_id

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @url = hash[:url]
      @status = hash[:status]
      @custom_payment_method_id = hash[:custom_payment_method_id]
    end
  end
end
