# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      product_id: :product_id,
      product_title: :product_title,
      variant_title: :variant_title,
      enabled: :enabled,
      commission: :commission
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      product_id: {required: true, schema: {kind: :integer}},
      product_title: {required: true, schema: {kind: :string}},
      variant_title: {required: true, schema: {kind: :string}},
      enabled: {required: true, schema: {kind: :literal, value: true}},
      commission: {required: true, schema: {kind: :model, name: "SellApp::ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItemPropertyCommission"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :product_id,
      :product_title,
      :variant_title,
      :enabled,
      :commission

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @product_id = hash[:product_id]
      @product_title = hash[:product_title]
      @variant_title = hash[:variant_title]
      @enabled = hash[:enabled]
      @commission = hash[:commission] ? SellApp::ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItemPropertyCommission.new(hash[:commission]) : nil
    end
  end
end
