# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkReplaceAffiliateProgramConfigurationRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      enabled: :enabled,
      settings: :settings,
      products: :products
    }.freeze

    SCHEMA = {
      enabled: {required: true, schema: {kind: :boolean}},
      settings: {required: true, schema: {kind: :model, name: "SellApp::ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettings"}},
      products: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertyProductsItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :enabled,
      :settings,
      :products

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @enabled = hash[:enabled]
      @settings = hash[:settings] ? SellApp::ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettings.new(hash[:settings]) : nil
      @products = hash[:products] ? hash[:products].map { |item| item ? SellApp::ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertyProductsItem.new(item) : nil } : nil
    end
  end
end
