# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkCancelCustomerSubscriptionImmediatelyResponseValue200ApplicationJson = SdkCancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJson
end
