# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  UpdateCustomerSubscriptionPaymentMethodResponseValue200ApplicationJsonPropertyData = CancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyData
end
