# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListBundleItemsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData = GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData
end
