# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateGroupResponseValue201ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      title: :title,
      order: :order,
      image: :image,
      unlisted: :unlisted,
      created_at: :created_at,
      updated_at: :updated_at,
      store_id: :store_id,
      section_id: :section_id,
      section_order: :section_order,
      products_linked: :products_linked,
      products: :products
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      title: {required: true, schema: {kind: :string}},
      order: {required: true, schema: {kind: :integer}},
      image: {required: true, schema: {kind: :nullable, inner: {kind: :model, name: "SellApp::CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImage"}}},
      unlisted: {required: true, schema: {kind: :boolean}},
      created_at: {required: true, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: true, schema: {kind: :string, format: "date-time"}},
      store_id: {required: true, schema: {kind: :integer}},
      section_id: {required: true, schema: {kind: :nullable, inner: {kind: :integer}}},
      section_order: {required: true, schema: {kind: :nullable, inner: {kind: :integer}}},
      products_linked: {required: true, schema: {kind: :integer}},
      products: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyProductsItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :title,
      :order,
      :image,
      :unlisted,
      :created_at,
      :updated_at,
      :store_id,
      :section_id,
      :section_order,
      :products_linked,
      :products

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @title = hash[:title]
      @order = hash[:order]
      @image = hash[:image] ? SellApp::CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyImage.new(hash[:image]) : nil
      @unlisted = hash[:unlisted]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
      @store_id = hash[:store_id]
      @section_id = hash[:section_id]
      @section_order = hash[:section_order]
      @products_linked = hash[:products_linked]
      @products = hash[:products] ? hash[:products].map { |item| item ? SellApp::CreateGroupResponseValue201ApplicationJsonPropertyDataPropertyProductsItem.new(item) : nil } : nil
    end
  end
end
