# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyPivot = GetProductWithinGroupResponseValue200ApplicationJsonPropertyDataPropertyPivot
end
