# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkDeleteGroupResponseValue200ApplicationJson = SdkCreateGroupResponseValue201ApplicationJson
end
