# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkSearchGroupsResponseValue200ApplicationJson = SdkListGroupsResponseValue200ApplicationJson
end
