# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem = ListProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItem
end
