# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkExchangeOAuthTokenResponseValue200ApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      token_type: :token_type,
      expires_in: :expires_in,
      access_token: :access_token,
      refresh_token: :refresh_token
    }.freeze

    SCHEMA = {
      token_type: {required: true, schema: {kind: :literal, value: "Bearer"}},
      expires_in: {required: true, schema: {kind: :literal, value: 3600}},
      access_token: {required: true, schema: {kind: :string}},
      refresh_token: {required: true, schema: {kind: :string}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :token_type,
      :expires_in,
      :access_token,
      :refresh_token

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @token_type = hash[:token_type]
      @expires_in = hash[:expires_in]
      @access_token = hash[:access_token]
      @refresh_token = hash[:refresh_token]
    end
  end
end
