# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkGetOAuthAuthorizationServerMetadataResponseValue200ApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      issuer: :issuer,
      authorization_endpoint: :authorization_endpoint,
      token_endpoint: :token_endpoint,
      revocation_endpoint: :revocation_endpoint,
      response_types_supported: :response_types_supported,
      grant_types_supported: :grant_types_supported,
      code_challenge_methods_supported: :code_challenge_methods_supported,
      token_endpoint_auth_methods_supported: :token_endpoint_auth_methods_supported,
      revocation_endpoint_auth_methods_supported: :revocation_endpoint_auth_methods_supported,
      scopes_supported: :scopes_supported
    }.freeze

    SCHEMA = {
      issuer: {required: true, schema: {kind: :string, format: "uri"}},
      authorization_endpoint: {required: true, schema: {kind: :string, format: "uri"}},
      token_endpoint: {required: true, schema: {kind: :string, format: "uri"}},
      revocation_endpoint: {required: true, schema: {kind: :string, format: "uri"}},
      response_types_supported: {required: true, schema: {kind: :array, items: {kind: :string}}},
      grant_types_supported: {required: true, schema: {kind: :array, items: {kind: :string}}},
      code_challenge_methods_supported: {required: true, schema: {kind: :array, items: {kind: :string}}},
      token_endpoint_auth_methods_supported: {required: true, schema: {kind: :array, items: {kind: :string}}},
      revocation_endpoint_auth_methods_supported: {required: true, schema: {kind: :array, items: {kind: :string}}},
      scopes_supported: {required: true, schema: {kind: :array, items: {kind: :string}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :issuer,
      :authorization_endpoint,
      :token_endpoint,
      :revocation_endpoint,
      :response_types_supported,
      :grant_types_supported,
      :code_challenge_methods_supported,
      :token_endpoint_auth_methods_supported,
      :revocation_endpoint_auth_methods_supported,
      :scopes_supported

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @issuer = hash[:issuer]
      @authorization_endpoint = hash[:authorization_endpoint]
      @token_endpoint = hash[:token_endpoint]
      @revocation_endpoint = hash[:revocation_endpoint]
      @response_types_supported = hash[:response_types_supported]
      @grant_types_supported = hash[:grant_types_supported]
      @code_challenge_methods_supported = hash[:code_challenge_methods_supported]
      @token_endpoint_auth_methods_supported = hash[:token_endpoint_auth_methods_supported]
      @revocation_endpoint_auth_methods_supported = hash[:revocation_endpoint_auth_methods_supported]
      @scopes_supported = hash[:scopes_supported]
    end
  end
end
