# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateCreditsProductResponseValue201ApplicationJsonPropertyDataPropertyDefaultVariant < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      price_cents: :price_cents,
      currency: :currency,
      minimum_purchase_quantity: :minimum_purchase_quantity,
      maximum_purchase_quantity: :maximum_purchase_quantity,
      quantity_increment: :quantity_increment,
      stock: :stock,
      payment_methods: :payment_methods,
      rate_tiers: :rate_tiers
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      price_cents: {required: true, schema: {kind: :integer, minimum: 0}},
      currency: {required: true, schema: {kind: :string}},
      minimum_purchase_quantity: {required: true, schema: {kind: :integer, minimum: 1}},
      maximum_purchase_quantity: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      quantity_increment: {required: true, schema: {kind: :integer, minimum: 1}},
      stock: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 0}}},
      payment_methods: {required: true, schema: {kind: :array, items: {kind: :string}}},
      rate_tiers: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::CreateCreditsProductResponseValue201ApplicationJsonPropertyDataPropertyDefaultVariantValuePropertyRateTiersItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :price_cents,
      :currency,
      :minimum_purchase_quantity,
      :maximum_purchase_quantity,
      :quantity_increment,
      :stock,
      :payment_methods,
      :rate_tiers

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @price_cents = hash[:price_cents]
      @currency = hash[:currency]
      @minimum_purchase_quantity = hash[:minimum_purchase_quantity]
      @maximum_purchase_quantity = hash[:maximum_purchase_quantity]
      @quantity_increment = hash[:quantity_increment]
      @stock = hash[:stock]
      @payment_methods = hash[:payment_methods]
      @rate_tiers = hash[:rate_tiers] ? hash[:rate_tiers].map { |item| item ? SellApp::CreateCreditsProductResponseValue201ApplicationJsonPropertyDataPropertyDefaultVariantValuePropertyRateTiersItem.new(item) : nil } : nil
    end
  end
end
