# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class DeleteCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariant < SellApp::Types::BaseModel
    HASH_ATTRS = {
      state: :state,
      variant_count: :variant_count
    }.freeze

    SCHEMA = {
      state: {required: true, schema: {kind: :enum, values: ["missing_default_variant", "multiple_default_variants"]}},
      variant_count: {required: true, schema: {kind: :integer, minimum: 0}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :state,
      :variant_count

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @state = hash[:state]
      @variant_count = hash[:variant_count]
    end
  end
end
