# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class RecordCreditTransactionResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      store_id: :store_id,
      customer_id: :customer_id,
      product_id: :product_id,
      kind: :kind,
      amount_units: :amount_units,
      balance_after_units: :balance_after_units,
      idempotency_key: :idempotency_key,
      source_type: :source_type,
      source_id: :source_id,
      reason: :reason,
      metadata: :metadata,
      actor_user_id: :actor_user_id,
      created_at: :created_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      store_id: {required: true, schema: {kind: :integer}},
      customer_id: {required: true, schema: {kind: :integer}},
      product_id: {required: true, schema: {kind: :integer}},
      kind: {required: true, schema: {kind: :enum, values: ["grant", "consumption", "adjustment"]}},
      amount_units: {required: true, schema: {kind: :integer}},
      balance_after_units: {required: true, schema: {kind: :integer, minimum: 0}},
      idempotency_key: {required: true, schema: {kind: :string, max: 128}},
      source_type: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      source_id: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      reason: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      metadata: {required: false, schema: {kind: :model, name: "SellApp::RecordCreditTransactionResponseValue200ApplicationJsonPropertyDataPropertyMetadata"}},
      actor_user_id: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      created_at: {required: false, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :store_id,
      :customer_id,
      :product_id,
      :kind,
      :amount_units,
      :balance_after_units,
      :idempotency_key,
      :source_type,
      :source_id,
      :reason,
      :metadata,
      :actor_user_id,
      :created_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @store_id = hash[:store_id]
      @customer_id = hash[:customer_id]
      @product_id = hash[:product_id]
      @kind = hash[:kind]
      @amount_units = hash[:amount_units]
      @balance_after_units = hash[:balance_after_units]
      @idempotency_key = hash[:idempotency_key]
      @source_type = hash[:source_type]
      @source_id = hash[:source_id]
      @reason = hash[:reason]
      @metadata = hash[:metadata] ? SellApp::RecordCreditTransactionResponseValue200ApplicationJsonPropertyDataPropertyMetadata.new(hash[:metadata]) : nil
      @actor_user_id = hash[:actor_user_id]
      @created_at = hash[:created_at]
    end
  end
end
