# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkRecordCreditTransactionRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      customer_id: :customer_id,
      product_id: :product_id,
      kind: :kind,
      amount_units: :amount_units,
      idempotency_key: :idempotency_key,
      reason: :reason,
      source_type: :source_type,
      source_id: :source_id,
      metadata: :metadata
    }.freeze

    SCHEMA = {
      customer_id: {required: true, schema: {kind: :integer}},
      product_id: {required: true, schema: {kind: :integer}},
      kind: {required: true, schema: {kind: :enum, values: ["grant", "consumption", "adjustment"]}},
      amount_units: {required: true, schema: {kind: :integer}},
      idempotency_key: {required: true, schema: {kind: :string, min: 1, max: 128}},
      reason: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 1000}}},
      source_type: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 64}}},
      source_id: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 128}}},
      metadata: {required: false, schema: {kind: :model, name: "SellApp::RecordCreditTransactionRequestApplicationJsonPropertyMetadata"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :customer_id,
      :product_id,
      :kind,
      :amount_units,
      :idempotency_key,
      :reason,
      :source_type,
      :source_id,
      :metadata

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @customer_id = hash[:customer_id]
      @product_id = hash[:product_id]
      @kind = hash[:kind]
      @amount_units = hash[:amount_units]
      @idempotency_key = hash[:idempotency_key]
      @reason = hash[:reason]
      @source_type = hash[:source_type]
      @source_id = hash[:source_id]
      @metadata = hash[:metadata] ? SellApp::RecordCreditTransactionRequestApplicationJsonPropertyMetadata.new(hash[:metadata]) : nil
    end
  end
end
