# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CancelSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      product_subscription_id: :product_subscription_id,
      subscription_id: :subscription_id,
      action: :action,
      status: :status,
      provider: :provider,
      customer_message: :customer_message,
      confirmed_at: :confirmed_at,
      failed_at: :failed_at,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: false, schema: {kind: :integer}},
      product_subscription_id: {required: false, schema: {kind: :integer}},
      subscription_id: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      action: {required: false, schema: {kind: :enum, values: ["pause", "resume", "cancel_at_period_end", "cancel_immediately", "update_payment_method", "change_plan", "shift_billing_date"]}},
      status: {required: false, schema: {kind: :enum, values: ["pending", "confirmed", "failed", "expired", "dismissed", "force_resolved"]}},
      provider: {required: false, schema: {kind: :string}},
      customer_message: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      confirmed_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      failed_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      created_at: {required: false, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: false, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :product_subscription_id,
      :subscription_id,
      :action,
      :status,
      :provider,
      :customer_message,
      :confirmed_at,
      :failed_at,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @product_subscription_id = hash[:product_subscription_id]
      @subscription_id = hash[:subscription_id]
      @action = hash[:action]
      @status = hash[:status]
      @provider = hash[:provider]
      @customer_message = hash[:customer_message]
      @confirmed_at = hash[:confirmed_at]
      @failed_at = hash[:failed_at]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
