# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer = CancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyDataPropertyCustomer
end
