# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkSearchSubscriptionsResponseValue200ApplicationJson = SdkListSubscriptionsResponseValue200ApplicationJson
end
