# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkResumeSubscriptionRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      idempotency_key: :idempotency_key
    }.freeze

    SCHEMA = {
      idempotency_key: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 128}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor :idempotency_key

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @idempotency_key = hash[:idempotency_key]
    end
  end
end
