# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkPauseSubscriptionRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      idempotency_key: :idempotency_key,
      resume_at: :resume_at,
      reason: :reason
    }.freeze

    SCHEMA = {
      idempotency_key: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 128}}},
      resume_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      reason: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 500}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :idempotency_key,
      :resume_at,
      :reason

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @idempotency_key = hash[:idempotency_key]
      @resume_at = hash[:resume_at]
      @reason = hash[:reason]
    end
  end
end
