# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListDisputesResponseValue200ApplicationJsonPropertyDataItemPropertySource = GetDisputeResponseValue200ApplicationJsonPropertyDataPropertySource
end
