# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class Bookings
    sig { params(client: SellApp::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        limit: T.nilable(Integer),
        page: T.nilable(Integer),
        pagination: T.nilable(T::Boolean),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkListAppointmentsResponseValue200ApplicationJson)
    end
    def list(limit:, page:, pagination:, request_options:); end

    sig do
      params(
        filters: T.nilable(T::Array[SellApp::SearchAppointmentsRequestApplicationJsonPropertyFiltersItem]),
        sort: T.nilable(T::Array[SellApp::SearchAppointmentsRequestApplicationJsonPropertySortItem]),
        search: T.nilable(SellApp::SearchAppointmentsRequestApplicationJsonPropertySearch),
        includes: T.nilable(T::Array[SellApp::SearchAppointmentsRequestApplicationJsonPropertyIncludesItem]),
        limit: T.nilable(Integer),
        page: T.nilable(Integer),
        pagination: T.nilable(T::Boolean),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkSearchAppointmentsResponseValue200ApplicationJson)
    end
    def search(filters:, sort:, search:, includes:, limit:, page:, pagination:, request_options:); end

    sig do
      params(
        booking: String,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkGetAppointmentResponseValue200ApplicationJson)
    end
    def get(booking:, request_options:); end

    sig do
      params(
        booking: String,
        slot_start_at: String,
        timezone: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkUpdateAppointmentResponseValue200ApplicationJson)
    end
    def update(booking:, slot_start_at:, timezone:, request_options:); end

    sig do
      params(
        booking: String,
        status: String,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkCancelAppointmentResponseValue200ApplicationJson)
    end
    def cancel(booking:, status:, request_options:); end

  end
end
