# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(Integer)) }
    def id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def id=(value); end

    sig { returns(T.nilable(Integer)) }
    def product_subscription_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def product_subscription_id=(value); end

    sig { returns(T.nilable(String)) }
    def subscription_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def subscription_id=(value); end

    sig { returns(T.nilable(String)) }
    def action; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def action=(value); end

    sig { returns(T.nilable(String)) }
    def status; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def status=(value); end

    sig { returns(T.nilable(String)) }
    def provider; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def provider=(value); end

    sig { returns(T.nilable(String)) }
    def customer_message; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def customer_message=(value); end

    sig { returns(T.nilable(String)) }
    def confirmed_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def confirmed_at=(value); end

    sig { returns(T.nilable(String)) }
    def failed_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def failed_at=(value); end

    sig { returns(T.nilable(String)) }
    def created_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def created_at=(value); end

    sig { returns(T.nilable(String)) }
    def updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
