# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CoursesLessons
    sig { params(client: SellApp::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        course: String,
        section: Integer,
        title: String,
        type: String,
        content: T.nilable(String),
        is_preview: T.nilable(T::Boolean),
        is_published: T.nilable(T::Boolean),
        assignment: T.nilable(SellApp::CreateCourseLessonRequestApplicationJsonPropertyAssignment),
        questions: T.nilable(T::Array[SellApp::CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem]),
        expected_updated_at: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkCreateCourseLessonResponseValue201ApplicationJson)
    end
    def create(course:, section:, title:, type:, content:, is_preview:, is_published:, assignment:, questions:, expected_updated_at:, request_options:); end

    sig do
      params(
        course: String,
        lesson: Integer,
        title: T.nilable(String),
        type: T.nilable(String),
        content: T.nilable(String),
        is_preview: T.nilable(T::Boolean),
        is_published: T.nilable(T::Boolean),
        assignment: T.nilable(SellApp::ReplaceCourseLessonRequestApplicationJsonPropertyAssignment),
        questions: T.nilable(T::Array[SellApp::ReplaceCourseLessonRequestApplicationJsonPropertyQuestionsItem]),
        expected_updated_at: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkReplaceCourseLessonResponseValue200ApplicationJson)
    end
    def replace(course:, lesson:, title:, type:, content:, is_preview:, is_published:, assignment:, questions:, expected_updated_at:, request_options:); end

    sig do
      params(
        course: String,
        lesson: Integer,
        title: T.nilable(String),
        type: T.nilable(String),
        content: T.nilable(String),
        is_preview: T.nilable(T::Boolean),
        is_published: T.nilable(T::Boolean),
        assignment: T.nilable(SellApp::UpdateCourseLessonRequestApplicationJsonPropertyAssignment),
        questions: T.nilable(T::Array[SellApp::UpdateCourseLessonRequestApplicationJsonPropertyQuestionsItem]),
        expected_updated_at: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkUpdateCourseLessonResponseValue200ApplicationJson)
    end
    def update(course:, lesson:, title:, type:, content:, is_preview:, is_published:, assignment:, questions:, expected_updated_at:, request_options:); end

    sig do
      params(
        course: String,
        lesson: Integer,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkDeleteCourseLessonResponseValue200ApplicationJson)
    end
    def delete(course:, lesson:, request_options:); end

    sig do
      params(
        course: String,
        resources: T::Array[SellApp::ReorderCourseLessonsRequestApplicationJsonPropertyResourcesItem],
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkReorderCourseLessonsResponseValue200ApplicationJson)
    end
    def reorder(course:, resources:, request_options:); end

  end
end
