# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatus
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[SellApp::CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatusPropertyHistoryItem]) }
    def history; end

    sig { params(value: T::Array[SellApp::CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatusPropertyHistoryItem]).returns(T::Array[SellApp::CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatusPropertyHistoryItem]) }
    def history=(value); end

    sig { returns(SellApp::CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatusPropertyStatus) }
    def status; end

    sig { params(value: SellApp::CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatusPropertyStatus).returns(SellApp::CreateInvoiceResponseValue201ApplicationJsonPropertyDataPropertyStatusPropertyStatus) }
    def status=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
