# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CreateAddOnDraftRequestApplicationJsonPropertyVariantPropertyPricingPropertyPrice
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def price; end

    sig { params(value: Integer).returns(Integer) }
    def price=(value); end

    sig { returns(String) }
    def currency; end

    sig { params(value: String).returns(String) }
    def currency=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
