# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def prompt; end

    sig { params(value: String).returns(String) }
    def prompt=(value); end

    sig { returns(String) }
    def question_type; end

    sig { params(value: String).returns(String) }
    def question_type=(value); end

    sig { returns(T.nilable(String)) }
    def solution; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def solution=(value); end

    sig { returns(T.nilable(T::Array[SellApp::CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemPropertyAnswersItem])) }
    def answers; end

    sig { params(value: T.nilable(T::Array[SellApp::CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemPropertyAnswersItem])).returns(T.nilable(T::Array[SellApp::CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemPropertyAnswersItem])) }
    def answers=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
