# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPayment
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee) }
    def fee; end

    sig { params(value: SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee).returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFee) }
    def fee=(value); end

    sig { returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyGateway) }
    def gateway; end

    sig { params(value: SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyGateway).returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyGateway) }
    def gateway=(value); end

    sig { returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertySubtotal) }
    def subtotal; end

    sig { params(value: SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertySubtotal).returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertySubtotal) }
    def subtotal=(value); end

    sig { returns(String) }
    def expires_at; end

    sig { params(value: String).returns(String) }
    def expires_at=(value); end

    sig { returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFullPrice) }
    def full_price; end

    sig { params(value: SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFullPrice).returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyFullPrice) }
    def full_price=(value); end

    sig { returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyOriginalAmount) }
    def original_amount; end

    sig { params(value: SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyOriginalAmount).returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyPaymentPropertyOriginalAmount) }
    def original_amount=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
