# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CreateBookingHoldResponseValue201ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def id; end

    sig { params(value: String).returns(String) }
    def id=(value); end

    sig { returns(String) }
    def slot_start_at; end

    sig { params(value: String).returns(String) }
    def slot_start_at=(value); end

    sig { returns(String) }
    def slot_end_at; end

    sig { params(value: String).returns(String) }
    def slot_end_at=(value); end

    sig { returns(Integer) }
    def quantity; end

    sig { params(value: Integer).returns(Integer) }
    def quantity=(value); end

    sig { returns(String) }
    def expires_at; end

    sig { params(value: String).returns(String) }
    def expires_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
