# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyStatus
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[String]) }
    def history; end

    sig { params(value: T::Array[String]).returns(T::Array[String]) }
    def history=(value); end

    sig { returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus) }
    def status; end

    sig { params(value: SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus).returns(SellApp::CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyStatusPropertyStatus) }
    def status=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
