# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class CustomerPortalOrderLineItem
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(T.nilable(Integer)) }
    def product_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def product_id=(value); end

    sig { returns(T.nilable(Integer)) }
    def product_variant_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def product_variant_id=(value); end

    sig { returns(T.nilable(String)) }
    def product_title; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def product_title=(value); end

    sig { returns(T.nilable(String)) }
    def variant_title; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def variant_title=(value); end

    sig { returns(Integer) }
    def quantity; end

    sig { params(value: Integer).returns(Integer) }
    def quantity=(value); end

    sig { returns(String) }
    def status; end

    sig { params(value: String).returns(String) }
    def status=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
