# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class DeleteProductVariantResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Boolean) }
    def remove_duplicate; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def remove_duplicate=(value); end

    sig { returns(String) }
    def parsing_mode; end

    sig { params(value: String).returns(String) }
    def parsing_mode=(value); end

    sig { returns(T.nilable(Integer)) }
    def stock; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def stock=(value); end

    sig { returns(T.nilable(String)) }
    def comment; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def comment=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def serials; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def serials=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
