# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def id; end

    sig { params(value: String).returns(String) }
    def id=(value); end

    sig { returns(String) }
    def name; end

    sig { params(value: String).returns(String) }
    def name=(value); end

    sig { returns(String) }
    def description; end

    sig { params(value: String).returns(String) }
    def description=(value); end

    sig { returns(String) }
    def category; end

    sig { params(value: String).returns(String) }
    def category=(value); end

    sig { returns(String) }
    def connection_type; end

    sig { params(value: String).returns(String) }
    def connection_type=(value); end

    sig { returns(String) }
    def status; end

    sig { params(value: String).returns(String) }
    def status=(value); end

    sig { returns(T::Boolean) }
    def enabled; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def enabled=(value); end

    sig { returns(String) }
    def health_status; end

    sig { params(value: String).returns(String) }
    def health_status=(value); end

    sig { returns(T::Boolean) }
    def configuration_supported; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def configuration_supported=(value); end

    sig { returns(T::Array[SellApp::GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem]) }
    def required_input; end

    sig { params(value: T::Array[SellApp::GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem]).returns(T::Array[SellApp::GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataPropertyRequiredInputItem]) }
    def required_input=(value); end

    sig { returns(T.nilable(String)) }
    def connect_url; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def connect_url=(value); end

    sig { returns(T.nilable(String)) }
    def configuration_url; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def configuration_url=(value); end

    sig { returns(String) }
    def status_url; end

    sig { params(value: String).returns(String) }
    def status_url=(value); end

    sig { returns(T.nilable(String)) }
    def actionable_error; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def actionable_error=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
