# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class GetCustomerResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(String) }
    def email; end

    sig { params(value: String).returns(String) }
    def email=(value); end

    sig { returns(T.nilable(String)) }
    def external_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def external_id=(value); end

    sig { returns(T.nilable(String)) }
    def name; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def name=(value); end

    sig { returns(T.nilable(String)) }
    def locale; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def locale=(value); end

    sig { returns(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyMetadata) }
    def metadata; end

    sig { params(value: SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyMetadata).returns(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyMetadata) }
    def metadata=(value); end

    sig { returns(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights) }
    def insights; end

    sig { params(value: SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights).returns(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyInsights) }
    def insights=(value); end

    sig { returns(T.nilable(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet)) }
    def wallet; end

    sig { params(value: T.nilable(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet)).returns(T.nilable(SellApp::GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet)) }
    def wallet=(value); end

    sig { returns(T.nilable(String)) }
    def created_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def created_at=(value); end

    sig { returns(T.nilable(String)) }
    def updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
