# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImage
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(String)) }
    def path; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def path=(value); end

    sig { returns(T.nilable(SellApp::GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata)) }
    def metadata; end

    sig { params(value: T.nilable(SellApp::GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata)).returns(T.nilable(SellApp::GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata)) }
    def metadata=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
