# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyPromotion
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def phase_id; end

    sig { params(value: Integer).returns(Integer) }
    def phase_id=(value); end

    sig { returns(Integer) }
    def promotion_id; end

    sig { params(value: Integer).returns(Integer) }
    def promotion_id=(value); end

    sig { returns(T.nilable(String)) }
    def name; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def name=(value); end

    sig { returns(T.nilable(String)) }
    def discount_type; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def discount_type=(value); end

    sig { returns(T.nilable(String)) }
    def discount_value; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def discount_value=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
