# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class GetVariantDeliverableConfigurationResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[String]) }
    def types; end

    sig { params(value: T::Array[String]).returns(T::Array[String]) }
    def types=(value); end

    sig { returns(SellApp::GetVariantDeliverableConfigurationResponseValue200ApplicationJsonPropertyDataPropertyData) }
    def data; end

    sig { params(value: SellApp::GetVariantDeliverableConfigurationResponseValue200ApplicationJsonPropertyDataPropertyData).returns(SellApp::GetVariantDeliverableConfigurationResponseValue200ApplicationJsonPropertyDataPropertyData) }
    def data=(value); end

    sig { returns(T::Boolean) }
    def webhook_configured; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def webhook_configured=(value); end

    sig { returns(String) }
    def updated_at; end

    sig { params(value: String).returns(String) }
    def updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
