# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class Groups
    sig { params(client: SellApp::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        limit: T.nilable(Integer),
        page: T.nilable(Integer),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkListGroupsResponseValue200ApplicationJson)
    end
    def list(limit:, page:, request_options:); end

    sig do
      params(
        title: String,
        unlisted: T::Boolean,
        order: T.nilable(Integer),
        product_ids: T.nilable(T::Array[Integer]),
        section_id: T.nilable(Integer),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkCreateGroupResponseValue201ApplicationJson)
    end
    def create(title:, unlisted:, order:, product_ids:, section_id:, request_options:); end

    sig do
      params(
        group: Integer,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkGetGroupResponseValue200ApplicationJson)
    end
    def get(group:, request_options:); end

    sig do
      params(
        group: Integer,
        title: T.nilable(String),
        unlisted: T.nilable(T::Boolean),
        order: T.nilable(Integer),
        product_ids: T.nilable(T::Array[Integer]),
        section_id: T.nilable(Integer),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkUpdateGroupResponseValue200ApplicationJson)
    end
    def update(group:, title:, unlisted:, order:, product_ids:, section_id:, request_options:); end

    sig do
      params(
        group: Integer,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkDeleteGroupResponseValue200ApplicationJson)
    end
    def delete(group:, request_options:); end

    sig do
      params(
        filters: T.nilable(T::Array[SellApp::SearchGroupsRequestApplicationJsonPropertyFiltersItem]),
        sort: T.nilable(T::Array[SellApp::SearchGroupsRequestApplicationJsonPropertySortItem]),
        search: T.nilable(SellApp::SearchGroupsRequestApplicationJsonPropertySearch),
        includes: T.nilable(T::Array[SellApp::SearchGroupsRequestApplicationJsonPropertyIncludesItem]),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkSearchGroupsResponseValue200ApplicationJson)
    end
    def search(filters:, sort:, search:, includes:, request_options:); end

  end
end
