# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class LicenseInstances
    sig { params(client: SellApp::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        limit: T.nilable(Integer),
        page: T.nilable(Integer),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkListLicenseInstancesResponseValue200ApplicationJson)
    end
    def list(limit:, page:, request_options:); end

  end
end
