# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class ListOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyTax
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(String)) }
    def id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def id=(value); end

    sig { returns(T.nilable(String)) }
    def rate; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def rate=(value); end

    sig { returns(T.nilable(Integer)) }
    def amount_cents; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def amount_cents=(value); end

    sig { returns(T.nilable(String)) }
    def country; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def country=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
