# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItem
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(String) }
    def domain; end

    sig { params(value: String).returns(String) }
    def domain=(value); end

    sig { returns(String) }
    def status; end

    sig { params(value: String).returns(String) }
    def status=(value); end

    sig { returns(T.nilable(String)) }
    def hostname_status; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def hostname_status=(value); end

    sig { returns(T.nilable(String)) }
    def ssl_status; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def ssl_status=(value); end

    sig { returns(T.nilable(SellApp::ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItemPropertyOwnershipVerification)) }
    def ownership_verification; end

    sig { params(value: T.nilable(SellApp::ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItemPropertyOwnershipVerification)).returns(T.nilable(SellApp::ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItemPropertyOwnershipVerification)) }
    def ownership_verification=(value); end

    sig { returns(T.nilable(T::Array[SellApp::ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItemPropertySslValidationRecordsItem])) }
    def ssl_validation_records; end

    sig { params(value: T.nilable(T::Array[SellApp::ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItemPropertySslValidationRecordsItem])).returns(T.nilable(T::Array[SellApp::ListCustomDomainsResponseValue200ApplicationJsonPropertyDataItemPropertySslValidationRecordsItem])) }
    def ssl_validation_records=(value); end

    sig { returns(String) }
    def cname_target; end

    sig { params(value: String).returns(String) }
    def cname_target=(value); end

    sig { returns(T.nilable(String)) }
    def last_checked_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def last_checked_at=(value); end

    sig { returns(T.nilable(String)) }
    def verified_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def verified_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
