# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemPropertyVideo
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def source; end

    sig { params(value: String).returns(String) }
    def source=(value); end

    sig { returns(T.nilable(String)) }
    def external_url; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def external_url=(value); end

    sig { returns(T.nilable(String)) }
    def mux_playback_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def mux_playback_id=(value); end

    sig { returns(T.nilable(String)) }
    def mux_status; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def mux_status=(value); end

    sig { returns(T.nilable(Integer)) }
    def duration_seconds; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def duration_seconds=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
