# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class ReplaceHighlightResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(String) }
    def title; end

    sig { params(value: String).returns(String) }
    def title=(value); end

    sig { returns(T::Boolean) }
    def hidden; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def hidden=(value); end

    sig { returns(T.nilable(Integer)) }
    def sort_order; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def sort_order=(value); end

    sig { returns(T.nilable(String)) }
    def published_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def published_at=(value); end

    sig { returns(T::Array[SellApp::ReplaceHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem]) }
    def media; end

    sig { params(value: T::Array[SellApp::ReplaceHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem]).returns(T::Array[SellApp::ReplaceHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem]) }
    def media=(value); end

    sig { returns(String) }
    def created_at; end

    sig { params(value: String).returns(String) }
    def created_at=(value); end

    sig { returns(String) }
    def updated_at; end

    sig { params(value: String).returns(String) }
    def updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
