# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class ReplaceCashbackRuleResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(Integer) }
    def percent_basis; end

    sig { params(value: Integer).returns(Integer) }
    def percent_basis=(value); end

    sig { returns(T.nilable(Integer)) }
    def maximum_cashback_cents; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def maximum_cashback_cents=(value); end

    sig { returns(T::Boolean) }
    def is_active; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def is_active=(value); end

    sig { returns(T::Array[Integer]) }
    def product_ids; end

    sig { params(value: T::Array[Integer]).returns(T::Array[Integer]) }
    def product_ids=(value); end

    sig { returns(T.nilable(String)) }
    def created_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def created_at=(value); end

    sig { returns(T.nilable(String)) }
    def updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def updated_at=(value); end

    sig { returns(T.nilable(String)) }
    def deleted_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def deleted_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
