# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class RewardCouponTemplates
    sig { params(client: SellApp::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        limit: T.nilable(Integer),
        page: T.nilable(Integer),
        pagination: T.nilable(T::Boolean),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkListRewardCouponTemplatesResponseValue200ApplicationJson)
    end
    def list(limit:, page:, pagination:, request_options:); end

    sig do
      params(
        name: String,
        type: String,
        discount: T.any(String, Float),
        store_wide: T::Boolean,
        redemption_mode: String,
        is_active: T::Boolean,
        listing_ids: T::Array[Integer],
        minimum_amount: T.nilable(T.any(String, Float)),
        maximum_discount_amount: T.nilable(T.any(String, Float)),
        expires_at: T.nilable(String),
        expires_after_days: T.nilable(Integer),
        expected_updated_at: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkCreateRewardCouponTemplateResponseValue201ApplicationJson)
    end
    def create(name:, type:, discount:, store_wide:, redemption_mode:, is_active:, listing_ids:, minimum_amount:, maximum_discount_amount:, expires_at:, expires_after_days:, expected_updated_at:, request_options:); end

    sig do
      params(
        filters: T.nilable(T::Array[SellApp::SearchRewardRulesRequestApplicationJsonPropertyFiltersItem]),
        sort: T.nilable(T::Array[SellApp::SearchRewardRulesRequestApplicationJsonPropertySortItem]),
        search: T.nilable(SellApp::SearchRewardRulesRequestApplicationJsonPropertySearch),
        includes: T.nilable(T::Array[SellApp::SearchRewardRulesRequestApplicationJsonPropertyIncludesItem]),
        limit: T.nilable(Integer),
        page: T.nilable(Integer),
        pagination: T.nilable(T::Boolean),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkSearchRewardCouponTemplatesResponseValue200ApplicationJson)
    end
    def search(filters:, sort:, search:, includes:, limit:, page:, pagination:, request_options:); end

    sig do
      params(
        reward_coupon_template: Integer,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkGetRewardCouponTemplateResponseValue200ApplicationJson)
    end
    def get(reward_coupon_template:, request_options:); end

    sig do
      params(
        reward_coupon_template: Integer,
        name: T.nilable(String),
        type: T.nilable(String),
        discount: T.nilable(T.any(String, Float)),
        store_wide: T.nilable(T::Boolean),
        minimum_amount: T.nilable(T.any(String, Float)),
        maximum_discount_amount: T.nilable(T.any(String, Float)),
        expires_at: T.nilable(String),
        expires_after_days: T.nilable(Integer),
        redemption_mode: T.nilable(String),
        is_active: T.nilable(T::Boolean),
        listing_ids: T.nilable(T::Array[Integer]),
        expected_updated_at: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkReplaceRewardCouponTemplateResponseValue200ApplicationJson)
    end
    def replace(reward_coupon_template:, name:, type:, discount:, store_wide:, minimum_amount:, maximum_discount_amount:, expires_at:, expires_after_days:, redemption_mode:, is_active:, listing_ids:, expected_updated_at:, request_options:); end

    sig do
      params(
        reward_coupon_template: Integer,
        name: T.nilable(String),
        type: T.nilable(String),
        discount: T.nilable(T.any(String, Float)),
        store_wide: T.nilable(T::Boolean),
        minimum_amount: T.nilable(T.any(String, Float)),
        maximum_discount_amount: T.nilable(T.any(String, Float)),
        expires_at: T.nilable(String),
        expires_after_days: T.nilable(Integer),
        redemption_mode: T.nilable(String),
        is_active: T.nilable(T::Boolean),
        listing_ids: T.nilable(T::Array[Integer]),
        expected_updated_at: T.nilable(String),
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkUpdateRewardCouponTemplateResponseValue200ApplicationJson)
    end
    def update(reward_coupon_template:, name:, type:, discount:, store_wide:, minimum_amount:, maximum_discount_amount:, expires_at:, expires_after_days:, redemption_mode:, is_active:, listing_ids:, expected_updated_at:, request_options:); end

  end
end
