# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkUpdateGroupRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(String)) }
    def title; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def title=(value); end

    sig { returns(T.nilable(T::Boolean)) }
    def unlisted; end

    sig { params(value: T.nilable(T::Boolean)).returns(T.nilable(T::Boolean)) }
    def unlisted=(value); end

    sig { returns(T.nilable(Integer)) }
    def order; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def order=(value); end

    sig { returns(T.nilable(T::Array[Integer])) }
    def product_ids; end

    sig { params(value: T.nilable(T::Array[Integer])).returns(T.nilable(T::Array[Integer])) }
    def product_ids=(value); end

    sig { returns(T.nilable(Integer)) }
    def section_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def section_id=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
