# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkReorderCourseLessonsResponseValue200ApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(SellApp::ReorderCourseLessonsResponseValue200ApplicationJsonPropertyData) }
    def data; end

    sig { params(value: SellApp::ReorderCourseLessonsResponseValue200ApplicationJsonPropertyData).returns(SellApp::ReorderCourseLessonsResponseValue200ApplicationJsonPropertyData) }
    def data=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
