# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkV2BatchUpdateCouponsRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(SellApp::V2BatchUpdateCouponsRequestApplicationJsonPropertyResources) }
    def resources; end

    sig { params(value: SellApp::V2BatchUpdateCouponsRequestApplicationJsonPropertyResources).returns(SellApp::V2BatchUpdateCouponsRequestApplicationJsonPropertyResources) }
    def resources=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
