# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkValidateLicenseKeyRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def license_key; end

    sig { params(value: String).returns(String) }
    def license_key=(value); end

    sig { returns(T.nilable(String)) }
    def instance_id; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def instance_id=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
