# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkV2SearchCouponsRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertyFiltersItem])) }
    def filters; end

    sig { params(value: T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertyFiltersItem])).returns(T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertyFiltersItem])) }
    def filters=(value); end

    sig { returns(T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertySortItem])) }
    def sort; end

    sig { params(value: T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertySortItem])).returns(T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertySortItem])) }
    def sort=(value); end

    sig { returns(T.nilable(SellApp::V2SearchCouponsRequestApplicationJsonPropertySearch)) }
    def search; end

    sig { params(value: T.nilable(SellApp::V2SearchCouponsRequestApplicationJsonPropertySearch)).returns(T.nilable(SellApp::V2SearchCouponsRequestApplicationJsonPropertySearch)) }
    def search=(value); end

    sig { returns(T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertyIncludesItem])) }
    def includes; end

    sig { params(value: T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertyIncludesItem])).returns(T.nilable(T::Array[SellApp::V2SearchCouponsRequestApplicationJsonPropertyIncludesItem])) }
    def includes=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
