# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkQueueVariantSerialImportRequestMultipartFormData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def file; end

    sig { params(value: String).returns(String) }
    def file=(value); end

    sig { returns(String) }
    def parsing_mode; end

    sig { params(value: String).returns(String) }
    def parsing_mode=(value); end

    sig { returns(T.nilable(String)) }
    def custom_delimiter; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def custom_delimiter=(value); end

    sig { returns(T.nilable(T::Boolean)) }
    def remove_duplicates; end

    sig { params(value: T.nilable(T::Boolean)).returns(T.nilable(T::Boolean)) }
    def remove_duplicates=(value); end

    sig { returns(T.nilable(String)) }
    def mode; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def mode=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
