# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkSearchProductVariantsResponseValue200ApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem]) }
    def data; end

    sig { params(value: T::Array[SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem]).returns(T::Array[SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyDataItem]) }
    def data=(value); end

    sig { returns(SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyLinks) }
    def links; end

    sig { params(value: SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyLinks).returns(SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyLinks) }
    def links=(value); end

    sig { returns(SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyMeta) }
    def meta; end

    sig { params(value: SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyMeta).returns(SellApp::SearchProductVariantsResponseValue200ApplicationJsonPropertyMeta) }
    def meta=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
