# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkUpdateCashbackRuleRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(Integer)) }
    def percent_basis; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def percent_basis=(value); end

    sig { returns(T.nilable(Integer)) }
    def maximum_cashback_cents; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def maximum_cashback_cents=(value); end

    sig { returns(T.nilable(T::Boolean)) }
    def is_active; end

    sig { params(value: T.nilable(T::Boolean)).returns(T.nilable(T::Boolean)) }
    def is_active=(value); end

    sig { returns(T.nilable(T::Array[Integer])) }
    def product_ids; end

    sig { params(value: T.nilable(T::Array[Integer])).returns(T.nilable(T::Array[Integer])) }
    def product_ids=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
