# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkCreateOrderReplacementRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(SellApp::CreateOrderReplacementRequestApplicationJsonPropertyProductVariants) }
    def product_variants; end

    sig { params(value: SellApp::CreateOrderReplacementRequestApplicationJsonPropertyProductVariants).returns(SellApp::CreateOrderReplacementRequestApplicationJsonPropertyProductVariants) }
    def product_variants=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
