# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkSearchOrderLineItemsRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(T::Array[SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItem])) }
    def filters; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItem])).returns(T.nilable(T::Array[SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItem])) }
    def filters=(value); end

    sig { returns(T.nilable(T::Array[SellApp::SearchOrderLineItemsRequestApplicationJsonPropertySortItem])) }
    def sort; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchOrderLineItemsRequestApplicationJsonPropertySortItem])).returns(T.nilable(T::Array[SellApp::SearchOrderLineItemsRequestApplicationJsonPropertySortItem])) }
    def sort=(value); end

    sig { returns(T.nilable(SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyPagination)) }
    def pagination; end

    sig { params(value: T.nilable(SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyPagination)).returns(T.nilable(SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyPagination)) }
    def pagination=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
