# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkCreateProductRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def title; end

    sig { params(value: String).returns(String) }
    def title=(value); end

    sig { returns(String) }
    def description; end

    sig { params(value: String).returns(String) }
    def description=(value); end

    sig { returns(String) }
    def visibility; end

    sig { params(value: String).returns(String) }
    def visibility=(value); end

    sig { returns(T.nilable(String)) }
    def slug; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def slug=(value); end

    sig { returns(T.nilable(String)) }
    def type; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def type=(value); end

    sig { returns(T.nilable(Integer)) }
    def section; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def section=(value); end

    sig { returns(T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyAdditionalInformationItem])) }
    def additional_information; end

    sig { params(value: T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyAdditionalInformationItem])).returns(T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyAdditionalInformationItem])) }
    def additional_information=(value); end

    sig { returns(T.nilable(SellApp::CreateProductRequestApplicationJsonPropertyOtherSettings)) }
    def other_settings; end

    sig { params(value: T.nilable(SellApp::CreateProductRequestApplicationJsonPropertyOtherSettings)).returns(T.nilable(SellApp::CreateProductRequestApplicationJsonPropertyOtherSettings)) }
    def other_settings=(value); end

    sig { returns(T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyVariantsItem])) }
    def variants; end

    sig { params(value: T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyVariantsItem])).returns(T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyVariantsItem])) }
    def variants=(value); end

    sig { returns(T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyBundleItemsItem])) }
    def bundle_items; end

    sig { params(value: T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyBundleItemsItem])).returns(T.nilable(T::Array[SellApp::CreateProductRequestApplicationJsonPropertyBundleItemsItem])) }
    def bundle_items=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
