# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkReplaceWalletBonusTierRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def minimum_top_up_cents; end

    sig { params(value: Integer).returns(Integer) }
    def minimum_top_up_cents=(value); end

    sig { returns(String) }
    def bonus_kind; end

    sig { params(value: String).returns(String) }
    def bonus_kind=(value); end

    sig { returns(T.nilable(Integer)) }
    def fixed_bonus_cents; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def fixed_bonus_cents=(value); end

    sig { returns(T.nilable(Integer)) }
    def percent_basis; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def percent_basis=(value); end

    sig { returns(T.nilable(Integer)) }
    def maximum_bonus_cents; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def maximum_bonus_cents=(value); end

    sig { returns(Integer) }
    def priority; end

    sig { params(value: Integer).returns(Integer) }
    def priority=(value); end

    sig { returns(T::Boolean) }
    def is_active; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def is_active=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
