# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkBatchCreateProductVariantsRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[SellApp::BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem]) }
    def resources; end

    sig { params(value: T::Array[SellApp::BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem]).returns(T::Array[SellApp::BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem]) }
    def resources=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
