# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkUpdateInvoiceStatusResponseValue200ApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPayment) }
    def payment; end

    sig { params(value: SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPayment).returns(SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPayment) }
    def payment=(value); end

    sig { returns(SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyStatus) }
    def status; end

    sig { params(value: SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyStatus).returns(SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyStatus) }
    def status=(value); end

    sig { returns(T::Array[SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyWebhooksItem]) }
    def webhooks; end

    sig { params(value: T::Array[SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyWebhooksItem]).returns(T::Array[SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyWebhooksItem]) }
    def webhooks=(value); end

    sig { returns(T.nilable(String)) }
    def feedback; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def feedback=(value); end

    sig { returns(String) }
    def created_at; end

    sig { params(value: String).returns(String) }
    def created_at=(value); end

    sig { returns(String) }
    def updated_at; end

    sig { params(value: String).returns(String) }
    def updated_at=(value); end

    sig { returns(Integer) }
    def store_id; end

    sig { params(value: Integer).returns(Integer) }
    def store_id=(value); end

    sig { returns(T.nilable(Integer)) }
    def coupon_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def coupon_id=(value); end

    sig { returns(T.nilable(Integer)) }
    def subscription_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def subscription_id=(value); end

    sig { returns(SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyCustomerInformation) }
    def customer_information; end

    sig { params(value: SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyCustomerInformation).returns(SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyCustomerInformation) }
    def customer_information=(value); end

    sig { returns(T::Array[SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyProductVariantsItem]) }
    def product_variants; end

    sig { params(value: T::Array[SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyProductVariantsItem]).returns(T::Array[SellApp::UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyProductVariantsItem]) }
    def product_variants=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
