# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkSearchProductsRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertyFiltersItem])) }
    def filters; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertyFiltersItem])).returns(T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertyFiltersItem])) }
    def filters=(value); end

    sig { returns(T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertySortItem])) }
    def sort; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertySortItem])).returns(T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertySortItem])) }
    def sort=(value); end

    sig { returns(T.nilable(SellApp::SearchProductsRequestApplicationJsonPropertySearch)) }
    def search; end

    sig { params(value: T.nilable(SellApp::SearchProductsRequestApplicationJsonPropertySearch)).returns(T.nilable(SellApp::SearchProductsRequestApplicationJsonPropertySearch)) }
    def search=(value); end

    sig { returns(T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertyIncludesItem])) }
    def includes; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertyIncludesItem])).returns(T.nilable(T::Array[SellApp::SearchProductsRequestApplicationJsonPropertyIncludesItem])) }
    def includes=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
