# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkSearchFeedbackResponseValue200ApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem]) }
    def data; end

    sig { params(value: T::Array[SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem]).returns(T::Array[SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyDataItem]) }
    def data=(value); end

    sig { returns(SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyLinks) }
    def links; end

    sig { params(value: SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyLinks).returns(SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyLinks) }
    def links=(value); end

    sig { returns(SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyMeta) }
    def meta; end

    sig { params(value: SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyMeta).returns(SellApp::SearchFeedbackResponseValue200ApplicationJsonPropertyMeta) }
    def meta=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
