# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkUpdateProductVariantPricingRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(SellApp::UpdateProductVariantPricingRequestApplicationJsonPropertyPricing)) }
    def pricing; end

    sig { params(value: T.nilable(SellApp::UpdateProductVariantPricingRequestApplicationJsonPropertyPricing)).returns(T.nilable(SellApp::UpdateProductVariantPricingRequestApplicationJsonPropertyPricing)) }
    def pricing=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def payment_methods; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def payment_methods=(value); end

    sig { returns(T.nilable(T::Array[String])) }
    def custom_payment_method_ids; end

    sig { params(value: T.nilable(T::Array[String])).returns(T.nilable(T::Array[String])) }
    def custom_payment_method_ids=(value); end

    sig { returns(T.nilable(T::Array[SellApp::UpdateProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem])) }
    def bulk_discount; end

    sig { params(value: T.nilable(T::Array[SellApp::UpdateProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem])).returns(T.nilable(T::Array[SellApp::UpdateProductVariantPricingRequestApplicationJsonPropertyBulkDiscountItem])) }
    def bulk_discount=(value); end

    sig { returns(T.nilable(String)) }
    def expected_updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def expected_updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
