# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SdkSearchProductsWithinGroupRequestApplicationJson
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertyFiltersItem])) }
    def filters; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertyFiltersItem])).returns(T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertyFiltersItem])) }
    def filters=(value); end

    sig { returns(T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertySortItem])) }
    def sort; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertySortItem])).returns(T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertySortItem])) }
    def sort=(value); end

    sig { returns(T.nilable(SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertySearch)) }
    def search; end

    sig { params(value: T.nilable(SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertySearch)).returns(T.nilable(SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertySearch)) }
    def search=(value); end

    sig { returns(T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertyIncludesItem])) }
    def includes; end

    sig { params(value: T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertyIncludesItem])).returns(T.nilable(T::Array[SellApp::SearchProductsWithinGroupRequestApplicationJsonPropertyIncludesItem])) }
    def includes=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
