# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SearchOrdersRequestApplicationJsonPropertyPagination
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T.nilable(Integer)) }
    def page; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def page=(value); end

    sig { returns(T.nilable(Integer)) }
    def limit; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def limit=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
