# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(String) }
    def path; end

    sig { params(value: String).returns(String) }
    def path=(value); end

    sig { returns(SellApp::SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadata) }
    def metadata; end

    sig { params(value: SellApp::SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadata).returns(SellApp::SearchProductsWithinGroupResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItemPropertyMetadata) }
    def metadata=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
