# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPayment
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyFee) }
    def fee; end

    sig { params(value: SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyFee).returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyFee) }
    def fee=(value); end

    sig { returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway) }
    def gateway; end

    sig { params(value: SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway).returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyGateway) }
    def gateway=(value); end

    sig { returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal) }
    def subtotal; end

    sig { params(value: SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal).returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertySubtotal) }
    def subtotal=(value); end

    sig { returns(String) }
    def expires_at; end

    sig { params(value: String).returns(String) }
    def expires_at=(value); end

    sig { returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyFullPrice) }
    def full_price; end

    sig { params(value: SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyFullPrice).returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyFullPrice) }
    def full_price=(value); end

    sig { returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmount) }
    def original_amount; end

    sig { params(value: SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmount).returns(SellApp::SearchInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyPaymentPropertyOriginalAmount) }
    def original_amount=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
