# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class StoreNotificationChannels
    sig { params(client: SellApp::BaseClient).void }
    def initialize(client); end

    sig do
      params(
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkListNotificationChannelsResponseValue200ApplicationJson)
    end
    def list(request_options:); end

    sig do
      params(
        channel: SellApp::CreateNotificationChannelRequestApplicationJsonPropertyChannel,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkCreateNotificationChannelResponseValue201ApplicationJson)
    end
    def create(channel:, request_options:); end

    sig do
      params(
        notification_channel: String,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkGetNotificationChannelResponseValue200ApplicationJson)
    end
    def get(notification_channel:, request_options:); end

    sig do
      params(
        notification_channel: String,
        channel: SellApp::ReplaceNotificationChannelRequestApplicationJsonPropertyChannel,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkReplaceNotificationChannelResponseValue200ApplicationJson)
    end
    def replace(notification_channel:, channel:, request_options:); end

    sig do
      params(
        notification_channel: String,
        channel: SellApp::UpdateNotificationChannelRequestApplicationJsonPropertyChannel,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkUpdateNotificationChannelResponseValue200ApplicationJson)
    end
    def update(notification_channel:, channel:, request_options:); end

    sig do
      params(
        notification_channel: String,
        request_options: T::Hash[Symbol, T.untyped]
      ).returns(SellApp::SdkDeleteNotificationChannelResponseValue200ApplicationJson)
    end
    def delete(notification_channel:, request_options:); end

  end
end
