# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricing
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Boolean) }
    def humble; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def humble=(value); end

    sig { returns(SellApp::UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyFrequency) }
    def frequency; end

    sig { params(value: SellApp::UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyFrequency).returns(SellApp::UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyFrequency) }
    def frequency=(value); end

    sig { returns(String) }
    def type; end

    sig { params(value: String).returns(String) }
    def type=(value); end

    sig { returns(SellApp::UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyPrice) }
    def price; end

    sig { params(value: SellApp::UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyPrice).returns(SellApp::UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyPrice) }
    def price=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
