# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class UpdateAffiliatePayoutStatusResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(Integer) }
    def affiliate_id; end

    sig { params(value: Integer).returns(Integer) }
    def affiliate_id=(value); end

    sig { returns(T.nilable(String)) }
    def affiliate_email; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def affiliate_email=(value); end

    sig { returns(Integer) }
    def amount_usd_cents; end

    sig { params(value: Integer).returns(Integer) }
    def amount_usd_cents=(value); end

    sig { returns(String) }
    def status; end

    sig { params(value: String).returns(String) }
    def status=(value); end

    sig { returns(T.nilable(String)) }
    def payout_method; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def payout_method=(value); end

    sig { returns(String) }
    def payout_account; end

    sig { params(value: String).returns(String) }
    def payout_account=(value); end

    sig { returns(Integer) }
    def referrals_count; end

    sig { params(value: Integer).returns(Integer) }
    def referrals_count=(value); end

    sig { returns(T.nilable(String)) }
    def created_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def created_at=(value); end

    sig { returns(T.nilable(String)) }
    def updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
