# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class UpdateVariantDeliverableFolderResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(String) }
    def name; end

    sig { params(value: String).returns(String) }
    def name=(value); end

    sig { returns(T.nilable(String)) }
    def description; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def description=(value); end

    sig { returns(T.nilable(Integer)) }
    def parent_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def parent_id=(value); end

    sig { returns(Integer) }
    def variant_id; end

    sig { params(value: Integer).returns(Integer) }
    def variant_id=(value); end

    sig { returns(Integer) }
    def sort_order; end

    sig { params(value: Integer).returns(Integer) }
    def sort_order=(value); end

    sig { returns(T.nilable(String)) }
    def created_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def created_at=(value); end

    sig { returns(T.nilable(String)) }
    def updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def updated_at=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
