# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class UpdateProductResponseValue200ApplicationJsonPropertyDataPropertyOtherSettings
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(T::Array[SellApp::ProductFaqItem]) }
    def faq; end

    sig { params(value: T::Array[SellApp::ProductFaqItem]).returns(T::Array[SellApp::ProductFaqItem]) }
    def faq=(value); end

    sig { returns(String) }
    def video_url; end

    sig { params(value: String).returns(String) }
    def video_url=(value); end

    sig { returns(String) }
    def redirect_url; end

    sig { params(value: String).returns(String) }
    def redirect_url=(value); end

    sig { returns(String) }
    def product_title; end

    sig { params(value: String).returns(String) }
    def product_title=(value); end

    sig { returns(String) }
    def product_description; end

    sig { params(value: String).returns(String) }
    def product_description=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
