# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class V2GetTicketResponseValue200ApplicationJsonPropertyData
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(String) }
    def title; end

    sig { params(value: String).returns(String) }
    def title=(value); end

    sig { returns(String) }
    def status; end

    sig { params(value: String).returns(String) }
    def status=(value); end

    sig { returns(SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyCustomer) }
    def customer; end

    sig { params(value: SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyCustomer).returns(SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyCustomer) }
    def customer=(value); end

    sig { returns(SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReference) }
    def reference; end

    sig { params(value: SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReference).returns(SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReference) }
    def reference=(value); end

    sig { returns(T.nilable(String)) }
    def created_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def created_at=(value); end

    sig { returns(T.nilable(String)) }
    def updated_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def updated_at=(value); end

    sig { returns(Integer) }
    def store_id; end

    sig { params(value: Integer).returns(Integer) }
    def store_id=(value); end

    sig { returns(Integer) }
    def archived; end

    sig { params(value: Integer).returns(Integer) }
    def archived=(value); end

    sig { returns(SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReadStatus) }
    def read_status; end

    sig { params(value: SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReadStatus).returns(SellApp::V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReadStatus) }
    def read_status=(value); end

    sig { returns(T.nilable(Integer)) }
    def order_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def order_id=(value); end

    sig { returns(T.nilable(String)) }
    def reason; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def reason=(value); end

    sig { returns(Integer) }
    def message_count; end

    sig { params(value: Integer).returns(Integer) }
    def message_count=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
