# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

# typed: strong

module SellApp
  class ValidateLicenseKeyResponseValue200ApplicationJsonPropertyDataPropertyLicenseKey
    sig { params(json: T.any(String, T::Hash[Symbol, T.untyped])).void }
    def initialize(json); end

    sig { returns(Integer) }
    def id; end

    sig { params(value: Integer).returns(Integer) }
    def id=(value); end

    sig { returns(String) }
    def key; end

    sig { params(value: String).returns(String) }
    def key=(value); end

    sig { returns(Integer) }
    def limit; end

    sig { params(value: Integer).returns(Integer) }
    def limit=(value); end

    sig { returns(Integer) }
    def active; end

    sig { params(value: Integer).returns(Integer) }
    def active=(value); end

    sig { returns(String) }
    def status; end

    sig { params(value: String).returns(String) }
    def status=(value); end

    sig { returns(T.nilable(String)) }
    def expires_at; end

    sig { params(value: T.nilable(String)).returns(T.nilable(String)) }
    def expires_at=(value); end

    sig { returns(T::Boolean) }
    def is_expired; end

    sig { params(value: T::Boolean).returns(T::Boolean) }
    def is_expired=(value); end

    sig { returns(Integer) }
    def store_id; end

    sig { params(value: Integer).returns(Integer) }
    def store_id=(value); end

    sig { returns(T.nilable(Integer)) }
    def order_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def order_id=(value); end

    sig { returns(T.nilable(Integer)) }
    def invoice_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def invoice_id=(value); end

    sig { returns(Integer) }
    def product_id; end

    sig { params(value: Integer).returns(Integer) }
    def product_id=(value); end

    sig { returns(Integer) }
    def variant_id; end

    sig { params(value: Integer).returns(Integer) }
    def variant_id=(value); end

    sig { returns(Integer) }
    def customer_id; end

    sig { params(value: Integer).returns(Integer) }
    def customer_id=(value); end

    sig { returns(T.nilable(Integer)) }
    def subscription_id; end

    sig { params(value: T.nilable(Integer)).returns(T.nilable(Integer)) }
    def subscription_id=(value); end

    sig { returns(String) }
    def created_at; end

    sig { params(value: String).returns(String) }
    def created_at=(value); end

    sig { returns(String) }
    def updated_at; end

    sig { params(value: String).returns(String) }
    def updated_at=(value); end

    sig { returns(Integer) }
    def instances_count; end

    sig { params(value: Integer).returns(Integer) }
    def instances_count=(value); end

    sig { returns(T::Hash[Symbol, T.untyped]) }
    def to_h; end

    sig { params(args: T.untyped).returns(String) }
    def to_json(*args); end
  end
end
