# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateVariantDeliverableFolderResponseValue201ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      name: :name,
      description: :description,
      parent_id: :parent_id,
      variant_id: :variant_id,
      sort_order: :sort_order,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      name: {required: true, schema: {kind: :string, max: 255}},
      description: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 255}}},
      parent_id: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      variant_id: {required: true, schema: {kind: :integer}},
      sort_order: {required: true, schema: {kind: :integer, minimum: 0}},
      created_at: {required: false, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: false, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :name,
      :description,
      :parent_id,
      :variant_id,
      :sort_order,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @name = hash[:name]
      @description = hash[:description]
      @parent_id = hash[:parent_id]
      @variant_id = hash[:variant_id]
      @sort_order = hash[:sort_order]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
