# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListVariantDeliverableFoldersResponseValue200ApplicationJsonPropertyDataItem = CreateVariantDeliverableFolderResponseValue201ApplicationJsonPropertyData
end
