# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class AddOnsParentProducts
    def initialize(client)
      @client = client
    end

    # List an add-on's parent products
    # @param addon [Integer] The addon path parameter.
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param pagination [Boolean, nil] Set to false to return at most 100 matching items in one data array without pagination links or metadata.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListAddOnSParentProductsResponseValue200ApplicationJson]
    def list(
      addon:,
      limit: 15,
      page: 1,
      pagination: true,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page,
        'pagination' => pagination
      }.compact
      SellApp::Types::BaseModel.validate_value!(addon, {kind: :integer}, "$request.addon")
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      SellApp::Types::BaseModel.validate_value!(pagination, {kind: :boolean}, "$request.pagination") unless pagination.nil?
      request_options = request_options.merge(operation_id: 'listAddOnSParentProducts', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/addons/#{SellApp::Util.encode_path(addon)}/parent-products",
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListAddOnSParentProductsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Replace an add-on's parent products
    # @param addon [Integer] The addon path parameter.
    # @param resources [Array<Integer>]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkReplaceAddOnSParentProductsResponseValue200ApplicationJson]
    def replace(
      addon:,
      resources:,
      request_options: {}
    )
      body = {
        'resources' => resources
      }
      SellApp::Types::BaseModel.validate_value!(addon, {kind: :integer}, "$request.addon")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkReplaceAddOnSParentProductsRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'replaceAddOnSParentProducts', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :put,
        path: "/v2/addons/#{SellApp::Util.encode_path(addon)}/parent-products",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkReplaceAddOnSParentProductsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
