# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class BundleItems
    def initialize(client)
      @client = client
    end

    # Retrieve a bundle item
    # @param bundle [Integer] The bundle path parameter.
    # @param item [Integer] The item path parameter.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetBundleItemResponseValue200ApplicationJson]
    def get(
      bundle:,
      item:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(bundle, {kind: :integer}, "$request.bundle")
      SellApp::Types::BaseModel.validate_value!(item, {kind: :integer}, "$request.item")
      request_options = request_options.merge(operation_id: 'getBundleItem', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/bundles/#{SellApp::Util.encode_path(bundle)}/items/#{SellApp::Util.encode_path(item)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetBundleItemResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # List bundle items
    # @param bundle [Integer] The bundle path parameter.
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListBundleItemsResponseValue200ApplicationJson]
    def list(
      bundle:,
      limit: 15,
      page: 1,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page
      }.compact
      SellApp::Types::BaseModel.validate_value!(bundle, {kind: :integer}, "$request.bundle")
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      request_options = request_options.merge(operation_id: 'listBundleItems', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/bundles/#{SellApp::Util.encode_path(bundle)}/items",
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListBundleItemsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Attach bundle items
    # @param bundle [Integer] The bundle path parameter.
    # @param resources [SellApp::AttachBundleItemsRequestApplicationJsonPropertyResources]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkAttachBundleItemsResponseValue200ApplicationJson]
    def attach(
      bundle:,
      resources:,
      request_options: {}
    )
      body = {
        'resources' => resources
      }
      SellApp::Types::BaseModel.validate_value!(bundle, {kind: :integer}, "$request.bundle")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkAttachBundleItemsRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'attachBundleItems', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :post,
        path: "/v2/bundles/#{SellApp::Util.encode_path(bundle)}/items/attach",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkAttachBundleItemsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Detach bundle items
    # @param bundle [Integer] The bundle path parameter.
    # @param resources [Array<Integer>]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkDetachBundleItemsResponseValue200ApplicationJson]
    def detach(
      bundle:,
      resources:,
      request_options: {}
    )
      body = {
        'resources' => resources
      }
      SellApp::Types::BaseModel.validate_value!(bundle, {kind: :integer}, "$request.bundle")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkDetachBundleItemsRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'detachBundleItems', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :delete,
        path: "/v2/bundles/#{SellApp::Util.encode_path(bundle)}/items/detach",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkDetachBundleItemsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
