# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class CreditsBalancesTransactions
    def initialize(client)
      @client = client
    end

    # List credit balance transactions
    # @param customer [Integer]
    # @param credit_product [Integer]
    # @param page [Integer, nil]
    # @param limit [Integer, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListCreditBalanceTransactionsResponseValue200ApplicationJson]
    def list(
      customer:,
      credit_product:,
      page: 1,
      limit: 15,
      request_options: {}
    )
      params = {
        'page' => page,
        'limit' => limit
      }.compact
      SellApp::Types::BaseModel.validate_value!(customer, {kind: :integer}, "$request.customer")
      SellApp::Types::BaseModel.validate_value!(credit_product, {kind: :integer}, "$request.creditProduct")
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      request_options = request_options.merge(operation_id: 'listCreditBalanceTransactions', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/credit-balances/#{SellApp::Util.encode_path(customer)}/#{SellApp::Util.encode_path(credit_product)}/transactions",
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListCreditBalanceTransactionsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
