# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class Customers
    def initialize(client)
      @client = client
    end

    # List customers
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param pagination [Boolean, nil] Set to false to return at most 100 matching customers without pagination metadata.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListCustomersResponseValue200ApplicationJson]
    def list(
      limit: 15,
      page: 1,
      pagination: true,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page,
        'pagination' => pagination
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      SellApp::Types::BaseModel.validate_value!(pagination, {kind: :boolean}, "$request.pagination") unless pagination.nil?
      request_options = request_options.merge(operation_id: 'listCustomers', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/customers',
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListCustomersResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Create a customer
    # @param external_id [String, nil]
    # @param email [String]
    # @param name [String, nil]
    # @param locale [String, nil]
    # @param metadata [SellApp::CreateCustomerRequestApplicationJsonPropertyMetadata, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateCustomerResponseValue201ApplicationJson]
    def create_customer(
      email:,
      external_id: nil,
      name: SellApp::OMIT,
      locale: SellApp::OMIT,
      metadata: nil,
      request_options: {}
    )
      body = {
        'external_id' => external_id,
        'email' => email,
        'metadata' => metadata
      }.compact
      body['name'] = name unless name.equal?(SellApp::OMIT)
      body['locale'] = locale unless locale.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateCustomerRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createCustomer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: '/v2/customers',
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateCustomerResponseValue201ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Search customers
    # @param filters [Array<SellApp::SearchCustomersRequestApplicationJsonPropertyFiltersItem>, nil]
    # @param sort [Array<SellApp::SearchCustomersRequestApplicationJsonPropertySortItem>, nil]
    # @param search [SellApp::SearchCustomersRequestApplicationJsonPropertySearch, nil]
    # @param includes [Array<SellApp::SearchCustomersRequestApplicationJsonPropertyIncludesItem>, nil]
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param pagination [Boolean, nil] Set to false to return at most 100 matching customers without pagination metadata.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkSearchCustomersResponseValue200ApplicationJson]
    def search(
      filters: nil,
      sort: nil,
      search: nil,
      includes: nil,
      limit: 15,
      page: 1,
      pagination: true,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page,
        'pagination' => pagination
      }.compact
      body = {
        'filters' => filters,
        'sort' => sort,
        'search' => search,
        'includes' => includes
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      SellApp::Types::BaseModel.validate_value!(pagination, {kind: :boolean}, "$request.pagination") unless pagination.nil?
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkSearchCustomersRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'searchCustomers', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :post,
        path: '/v2/customers/search',
        auth: true,
        params: params,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkSearchCustomersResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retrieve a customer
    # @param customer [Integer] The customer path parameter.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetCustomerResponseValue200ApplicationJson]
    def get(
      customer:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(customer, {kind: :integer}, "$request.customer")
      request_options = request_options.merge(operation_id: 'getCustomer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/customers/#{SellApp::Util.encode_path(customer)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetCustomerResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Update a customer
    # @param customer [Integer] The customer identifier.
    # @param email [String, nil]
    # @param name [String, nil]
    # @param locale [String, nil]
    # @param metadata [SellApp::UpdateCustomerRequestApplicationJsonPropertyMetadata, nil]
    # @param external_id [String, nil] May be assigned when unset; an existing value is immutable.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkUpdateCustomerResponseValue200ApplicationJson]
    def update_customer(
      customer:,
      email: nil,
      name: SellApp::OMIT,
      locale: SellApp::OMIT,
      metadata: nil,
      external_id: nil,
      request_options: {}
    )
      body = {
        'email' => email,
        'metadata' => metadata,
        'external_id' => external_id
      }.compact
      body['name'] = name unless name.equal?(SellApp::OMIT)
      body['locale'] = locale unless locale.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(customer, {kind: :integer}, "$request.customer")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkUpdateCustomerRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'updateCustomer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :patch,
        path: "/v2/customers/#{SellApp::Util.encode_path(customer)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkUpdateCustomerResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retrieve a customer by external ID
    # @param external_id [String] The externalId identifier.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetCustomerResponseValue200ApplicationJson]
    def get_customer_by_external_id(
      external_id:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(external_id, {kind: :string}, "$request.externalId")
      request_options = request_options.merge(operation_id: 'getCustomerByExternalId', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/customers/external/#{SellApp::Util.encode_path(external_id)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetCustomerResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Create or update a customer by external ID
    # @param external_id [String] Store-local external ID, 1–255 characters; whitespace-only values are invalid. URL-encode it as one path segment.
    # @param email [String]
    # @param name [String, nil]
    # @param locale [String, nil]
    # @param metadata [SellApp::UpsertCustomerRequestApplicationJsonPropertyMetadata, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkUpsertCustomerResponseValue200ApplicationJson]
    def upsert_by_external_id(
      external_id:,
      email:,
      name: SellApp::OMIT,
      locale: SellApp::OMIT,
      metadata: nil,
      request_options: {}
    )
      body = {
        'email' => email,
        'metadata' => metadata
      }.compact
      body['name'] = name unless name.equal?(SellApp::OMIT)
      body['locale'] = locale unless locale.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(external_id, {kind: :string, min: 1, max: 255}, "$request.externalId")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkUpsertCustomerRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'upsertCustomerByExternalId', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :put,
        path: "/v2/customers/external/#{SellApp::Util.encode_path(external_id)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkUpsertCustomerResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Update a customer by external ID
    # @param external_id [String] The externalId identifier.
    # @param email [String, nil]
    # @param name [String, nil]
    # @param locale [String, nil]
    # @param metadata [SellApp::UpdateCustomerRequestApplicationJsonPropertyMetadata, nil]
    # @param body_external_id [String, nil] May be assigned when unset; an existing value is immutable.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkUpdateCustomerResponseValue200ApplicationJson]
    def update_customer_by_external_id(
      external_id:,
      email: nil,
      name: SellApp::OMIT,
      locale: SellApp::OMIT,
      metadata: nil,
      body_external_id: nil,
      request_options: {}
    )
      body = {
        'email' => email,
        'metadata' => metadata,
        'external_id' => body_external_id
      }.compact
      body['name'] = name unless name.equal?(SellApp::OMIT)
      body['locale'] = locale unless locale.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(external_id, {kind: :string}, "$request.externalId")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkUpdateCustomerRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'updateCustomerByExternalId', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :patch,
        path: "/v2/customers/external/#{SellApp::Util.encode_path(external_id)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkUpdateCustomerResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
