# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class Events
    def initialize(client)
      @client = client
    end

    # List integration events
    # @param cursor [String, nil] Signed cursor bound to this filter set.
    # @param limit [Integer, nil] Maximum events to return.
    # @param type [String, nil] Return only this event type.
    # @param subject_type [String, nil] Return events for this subject type.
    # @param subject_id [String, nil] Return events for this subject identifier.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListIntegrationEventsResponseValue200ApplicationJson]
    def list_integration_events(
      cursor: nil,
      limit: 50,
      type: nil,
      subject_type: nil,
      subject_id: nil,
      request_options: {}
    )
      params = {
        'cursor' => cursor,
        'limit' => limit,
        'type' => type,
        'subject_type' => subject_type,
        'subject_id' => subject_id
      }.compact
      SellApp::Types::BaseModel.validate_value!(cursor, {kind: :string}, "$request.cursor") unless cursor.nil?
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(type, {kind: :string, max: 120}, "$request.type") unless type.nil?
      SellApp::Types::BaseModel.validate_value!(subject_type, {kind: :literal, value: "order"}, "$request.subject_type") unless subject_type.nil?
      SellApp::Types::BaseModel.validate_value!(subject_id, {kind: :string, max: 100}, "$request.subject_id") unless subject_id.nil?
      request_options = request_options.merge(operation_id: 'listIntegrationEvents', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/events',
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListIntegrationEventsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # List order events
    # @param order [Integer] The order identifier.
    # @param cursor [String, nil] Signed cursor bound to this filter set.
    # @param limit [Integer, nil] Maximum events to return.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListOrderEventsResponseValue200ApplicationJson]
    def list_order_events(
      order:,
      cursor: nil,
      limit: 50,
      request_options: {}
    )
      params = {
        'cursor' => cursor,
        'limit' => limit
      }.compact
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(cursor, {kind: :string}, "$request.cursor") unless cursor.nil?
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      request_options = request_options.merge(operation_id: 'listOrderEvents', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/events",
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListOrderEventsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
