# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class LicenseInstances
    def initialize(client)
      @client = client
    end

    # List all license instances
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListLicenseInstancesResponseValue200ApplicationJson]
    def list(
      limit: 15,
      page: 1,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      request_options = request_options.merge(operation_id: 'listLicenseInstances', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/license-key-instances',
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListLicenseInstancesResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
