# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class LicensesInstances
    def initialize(client)
      @client = client
    end

    # List license instances
    # @param license_key [Integer] The license key path parameter.
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListLicenseKeyInstancesResponseValue200ApplicationJson]
    def list(
      license_key:,
      limit: 15,
      page: 1,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page
      }.compact
      SellApp::Types::BaseModel.validate_value!(license_key, {kind: :integer}, "$request.license_key")
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      request_options = request_options.merge(operation_id: 'listLicenseKeyInstances', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/license-keys/#{SellApp::Util.encode_path(license_key)}/instances",
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListLicenseKeyInstancesResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retrieve a license instance
    # @param license_key [Integer] The license key path parameter.
    # @param instance [String] The instance path parameter.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetLicenseInstanceResponseValue200ApplicationJson]
    def get(
      license_key:,
      instance:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(license_key, {kind: :integer}, "$request.license_key")
      SellApp::Types::BaseModel.validate_value!(instance, {kind: :string}, "$request.instance")
      request_options = request_options.merge(operation_id: 'getLicenseInstance', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/license-keys/#{SellApp::Util.encode_path(license_key)}/instances/#{SellApp::Util.encode_path(instance)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetLicenseInstanceResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
