# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class LineItems
    def initialize(client)
      @client = client
    end

    # List order line items
    # @param limit [Integer, nil] Maximum number of line items per page.
    # @param page [Integer, nil] One-based result page.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListOrderLineItemsResponseValue200ApplicationJson]
    def list(
      limit: 15,
      page: 1,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      request_options = request_options.merge(operation_id: 'listOrderLineItems', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/line-items',
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListOrderLineItemsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Search order line items
    # @param filters [Array<SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItem>, nil]
    # @param sort [Array<SellApp::SearchOrderLineItemsRequestApplicationJsonPropertySortItem>, nil]
    # @param pagination [SellApp::SearchOrderLineItemsRequestApplicationJsonPropertyPagination, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkSearchOrderLineItemsResponseValue200ApplicationJson]
    def search(
      filters: nil,
      sort: nil,
      pagination: nil,
      request_options: {}
    )
      body = {
        'filters' => filters,
        'sort' => sort,
        'pagination' => pagination
      }.compact
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkSearchOrderLineItemsRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'searchOrderLineItems', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :post,
        path: '/v2/line-items/search',
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkSearchOrderLineItemsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retrieve an order line item
    # @param line_item [Integer] The purchase line-item ID.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetOrderLineItemResponseValue200ApplicationJson]
    def get(
      line_item:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(line_item, {kind: :integer}, "$request.lineItem")
      request_options = request_options.merge(operation_id: 'getOrderLineItem', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/line-items/#{SellApp::Util.encode_path(line_item)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetOrderLineItemResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
