# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class OAuthManagement
    def initialize(client)
      @client = client
    end

    # Read your CLI connection
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetOAuthInstallationResponseValue200ApplicationJson]
    def get_oauth_installation(request_options: {})
      request_options = request_options.merge(operation_id: 'getOAuthInstallation', credential_policy: {anonymous: false, apiKey: false, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: false, accessTokenRequiresStore: false}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/oauth/installation',
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetOAuthInstallationResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Disconnect your CLI connection
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [void]
    def delete_oauth_installation(request_options: {})
      request_options = request_options.merge(operation_id: 'deleteOAuthInstallation', credential_policy: {anonymous: false, apiKey: false, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: false, accessTokenRequiresStore: false}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :delete,
        path: '/v2/oauth/installation',
        auth: true,
        request_options: request_options
      )
      value = begin
        nil
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
