# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class Orders
    def initialize(client)
      @client = client
    end

    # List orders
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListOrdersResponseValue200ApplicationJson]
    def list(
      limit: 15,
      page: 1,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      request_options = request_options.merge(operation_id: 'listOrders', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/orders',
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListOrdersResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Create an order
    # @param customer_email [String]
    # @param customer_ip [String, nil]
    # @param payment_method [SellApp::Types::SdkCreateOrderRequestApplicationJsonPaymentMethod]
    # @param coupon [String, nil]
    # @param vat_id [String, nil]
    # @param country [String, nil]
    # @param affiliate [String, nil]
    # @param extra [SellApp::CreateOrderRequestApplicationJsonPropertyExtra, nil]
    # @param product_variants [SellApp::CreateOrderRequestApplicationJsonPropertyProductVariants]
    # @param custom_payment_method_id [String, nil] Required when payment_method is CUSTOM_PAYMENT_METHOD. ULID of an enabled custom payment method belonging to this store.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateOrderResponseValue201ApplicationJson]
    def create(
      customer_email:,
      payment_method:,
      product_variants:,
      customer_ip: SellApp::OMIT,
      coupon: nil,
      vat_id: nil,
      country: nil,
      affiliate: SellApp::OMIT,
      extra: nil,
      custom_payment_method_id: SellApp::OMIT,
      request_options: {}
    )
      body = {
        'customer_email' => customer_email,
        'payment_method' => payment_method,
        'coupon' => coupon,
        'vat_id' => vat_id,
        'country' => country,
        'extra' => extra,
        'product_variants' => product_variants
      }.compact
      body['customer_ip'] = customer_ip unless customer_ip.equal?(SellApp::OMIT)
      body['affiliate'] = affiliate unless affiliate.equal?(SellApp::OMIT)
      body['custom_payment_method_id'] = custom_payment_method_id unless custom_payment_method_id.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateOrderRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createOrder', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: '/v2/orders',
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateOrderResponseValue201ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Search orders
    # @param filters [Array<SellApp::SearchOrdersRequestApplicationJsonPropertyFiltersItem>, nil]
    # @param sort [Array<SellApp::SearchOrdersRequestApplicationJsonPropertySortItem>, nil]
    # @param pagination [SellApp::SearchOrdersRequestApplicationJsonPropertyPagination, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkSearchOrdersResponseValue200ApplicationJson]
    def search(
      filters: nil,
      sort: nil,
      pagination: nil,
      request_options: {}
    )
      body = {
        'filters' => filters,
        'sort' => sort,
        'pagination' => pagination
      }.compact
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkSearchOrdersRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'searchOrders', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :post,
        path: '/v2/orders/search',
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkSearchOrdersResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retrieve an order
    # @param order [Integer] The order path parameter.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetOrderResponseValue200ApplicationJson]
    def get(
      order:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      request_options = request_options.merge(operation_id: 'getOrder', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetOrderResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Update order status
    # @param order [Integer] The order identifier.
    # @param status [SellApp::Types::SdkUpdateOrderStatusRequestApplicationJsonStatus]
    # @param expected_status [SellApp::Types::ExpectedStatus, nil] Expected current status. A status update checks this under the order lock and returns 422 if the order has changed.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkUpdateOrderStatusResponseValue200ApplicationJson]
    def update_status(
      order:,
      status:,
      expected_status: SellApp::OMIT,
      request_options: {}
    )
      body = {
        'status' => status
      }
      body['expected_status'] = expected_status unless expected_status.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkUpdateOrderStatusRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'updateOrderStatus', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :patch,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/status",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkUpdateOrderStatusResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Create order checkout
    # @param order [Integer] The order identifier.
    # @param expected_status [SellApp::Types::ExpectedStatus, nil] Validated status value; checkout does not compare it with current status. Retrieve the order before retrying.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateOrderCheckoutResponseValue200ApplicationJson]
    def create_checkout(
      order:,
      expected_status: SellApp::OMIT,
      request_options: {}
    )
      body = {}
      body['expected_status'] = expected_status unless expected_status.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateOrderCheckoutRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createOrderCheckout', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/checkout",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateOrderCheckoutResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Issue replacements
    # @param order [Integer] The order identifier.
    # @param product_variants [SellApp::CreateOrderReplacementRequestApplicationJsonPropertyProductVariants]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateOrderReplacementResponseValue200ApplicationJson]
    def create_replacement(
      order:,
      product_variants:,
      request_options: {}
    )
      body = {
        'product_variants' => product_variants
      }
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateOrderReplacementRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createOrderReplacement', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/replacements",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateOrderReplacementResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Refund an order
    # @param order [Integer] The order identifier.
    # @param amount [String, nil] Decimal major-unit amount in the order currency, positive and no greater than remaining balance. Precision follows that currency. Omission/null/empty requests the full remaining balance.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateOrderRefundResponseValue200ApplicationJson]
    def create_refund(
      order:,
      amount: SellApp::OMIT,
      request_options: {}
    )
      body = {}
      body['amount'] = amount unless amount.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateOrderRefundRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createOrderRefund', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/refunds",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateOrderRefundResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retry fulfillment
    # @param order [Integer] The order identifier.
    # @param email [String, nil] Optional delivery recipient override. Omit or send null to use the order delivery email.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkRetryOrderFulfillmentResponseValue200ApplicationJson]
    def retry_fulfillment(
      order:,
      email: SellApp::OMIT,
      request_options: {}
    )
      body = {}
      body['email'] = email unless email.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkRetryOrderFulfillmentRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'retryOrderFulfillment', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/fulfillment-retries",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkRetryOrderFulfillmentResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retry dynamic delivery
    # @param order [Integer] The order identifier.
    # @param delivered_product_id [Integer] Delivered product record ID, not a catalog product or order line-item ID. The public order-deliverables response does not currently expose this ID; obtain it from an authorized integration context before requesting a retry.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkRetryOrderDynamicDeliveryResponseValue202ApplicationJson]
    def retry_dynamic_delivery(
      order:,
      delivered_product_id:,
      request_options: {}
    )
      body = {
        'delivered_product_id' => delivered_product_id
      }
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkRetryOrderDynamicDeliveryRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'retryOrderDynamicDelivery', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/dynamic-delivery-retries",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkRetryOrderDynamicDeliveryResponseValue202ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Send fulfillment notifications
    # @param order [Integer] The order identifier.
    # @param email [String, nil] Optional delivery recipient override. Omit or send null to use the order delivery email.
    # @param product_variant_ids [Array<Integer>, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkSendOrderFulfillmentNotificationsResponseValue200ApplicationJson]
    def send_fulfillment_notifications(
      order:,
      email: SellApp::OMIT,
      product_variant_ids: SellApp::OMIT,
      request_options: {}
    )
      body = {}
      body['email'] = email unless email.equal?(SellApp::OMIT)
      body['product_variant_ids'] = product_variant_ids unless product_variant_ids.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkSendOrderFulfillmentNotificationsRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'sendOrderFulfillmentNotifications', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/fulfillment-notifications",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkSendOrderFulfillmentNotificationsResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # List order deliverables
    # @param order [Integer] The order identifier.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListOrderDeliverablesResponseValue200ApplicationJson]
    def list_deliverables(
      order:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      request_options = request_options.merge(operation_id: 'listOrderDeliverables', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/deliverables",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListOrderDeliverablesResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Create and pay an order from a wallet
    # @param customer_email [String]
    # @param customer_ip [String, nil]
    # @param coupon [String, nil]
    # @param vat_id [String, nil]
    # @param country [String, nil]
    # @param affiliate [String, nil]
    # @param extra [SellApp::CreateWalletOrderRequestApplicationJsonPropertyExtra, nil]
    # @param product_variants [SellApp::CreateWalletOrderRequestApplicationJsonPropertyProductVariants]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateWalletOrderResponseValue201ApplicationJson]
    def create_from_wallet(
      customer_email:,
      product_variants:,
      customer_ip: SellApp::OMIT,
      coupon: nil,
      vat_id: nil,
      country: nil,
      affiliate: SellApp::OMIT,
      extra: nil,
      request_options: {}
    )
      body = {
        'customer_email' => customer_email,
        'coupon' => coupon,
        'vat_id' => vat_id,
        'country' => country,
        'extra' => extra,
        'product_variants' => product_variants
      }.compact
      body['customer_ip'] = customer_ip unless customer_ip.equal?(SellApp::OMIT)
      body['affiliate'] = affiliate unless affiliate.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateWalletOrderRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createWalletOrder', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: '/v2/orders/wallet',
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateWalletOrderResponseValue201ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Pay an existing order from its customer wallet
    # @param order [Integer]
    # @param expected_status [SellApp::Types::ExpectedStatus, nil]
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkPayOrderFromWalletResponseValue200ApplicationJson]
    def pay_from_wallet(
      order:,
      expected_status: SellApp::OMIT,
      request_options: {}
    )
      body = {}
      body['expected_status'] = expected_status unless expected_status.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(order, {kind: :integer}, "$request.order")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkPayOrderFromWalletRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'payOrderFromWallet', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: true)
      response = @client.request(
        method: :post,
        path: "/v2/orders/#{SellApp::Util.encode_path(order)}/wallet-payments",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkPayOrderFromWalletResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
