# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'json'

module SellApp
  class UpsellOffers
    def initialize(client)
      @client = client
    end

    # List upsell offers
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param pagination [Boolean, nil] Set to false to return at most 100 matching items in one data array without pagination links or metadata.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkListUpsellOffersResponseValue200ApplicationJson]
    def list(
      limit: 15,
      page: 1,
      pagination: true,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page,
        'pagination' => pagination
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      SellApp::Types::BaseModel.validate_value!(pagination, {kind: :boolean}, "$request.pagination") unless pagination.nil?
      request_options = request_options.merge(operation_id: 'listUpsellOffers', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: '/v2/upsell-offers',
        auth: true,
        params: params,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkListUpsellOffersResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Create an upsell offer
    # @param name [String]
    # @param description [String, nil]
    # @param is_active [Boolean]
    # @param source_listing_id [Integer]
    # @param source_variant_id [Integer, nil]
    # @param minimum_order_total_usd_cents [Integer, nil] Integer USD cents, for example 1000 for USD 10.00.
    # @param maximum_order_total_usd_cents [Integer, nil] Integer USD cents. When present, must be greater than or equal to minimum_order_total_usd_cents.
    # @param starts_at [String, nil]
    # @param ends_at [String, nil] Must be after or equal to starts_at.
    # @param available_for_days [Integer, nil]
    # @param max_accepts_per_customer [Integer, nil]
    # @param expected_version [Integer, nil] Required optimistic concurrency token for updates. Use the version from the latest response; stale versions are rejected with 422.
    # @param items [Array<SellApp::CreateUpsellOfferRequestApplicationJsonPropertyItemsItem>] Complete ordered target-item set. Target variant IDs must be unique and belong to their target product in this store.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkCreateUpsellOfferResponseValue201ApplicationJson]
    def create(
      name:,
      is_active:,
      source_listing_id:,
      items:,
      description: SellApp::OMIT,
      source_variant_id: SellApp::OMIT,
      minimum_order_total_usd_cents: SellApp::OMIT,
      maximum_order_total_usd_cents: SellApp::OMIT,
      starts_at: SellApp::OMIT,
      ends_at: SellApp::OMIT,
      available_for_days: SellApp::OMIT,
      max_accepts_per_customer: SellApp::OMIT,
      expected_version: nil,
      request_options: {}
    )
      body = {
        'name' => name,
        'is_active' => is_active,
        'source_listing_id' => source_listing_id,
        'expected_version' => expected_version,
        'items' => items
      }.compact
      body['description'] = description unless description.equal?(SellApp::OMIT)
      body['source_variant_id'] = source_variant_id unless source_variant_id.equal?(SellApp::OMIT)
      body['minimum_order_total_usd_cents'] = minimum_order_total_usd_cents unless minimum_order_total_usd_cents.equal?(SellApp::OMIT)
      body['maximum_order_total_usd_cents'] = maximum_order_total_usd_cents unless maximum_order_total_usd_cents.equal?(SellApp::OMIT)
      body['starts_at'] = starts_at unless starts_at.equal?(SellApp::OMIT)
      body['ends_at'] = ends_at unless ends_at.equal?(SellApp::OMIT)
      body['available_for_days'] = available_for_days unless available_for_days.equal?(SellApp::OMIT)
      body['max_accepts_per_customer'] = max_accepts_per_customer unless max_accepts_per_customer.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkCreateUpsellOfferRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'createUpsellOffer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :post,
        path: '/v2/upsell-offers',
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkCreateUpsellOfferResponseValue201ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Search upsell offers
    # @param filters [Array<SellApp::SearchUpsellOffersRequestApplicationJsonPropertyFiltersItem>, nil]
    # @param sort [Array<SellApp::SearchUpsellOffersRequestApplicationJsonPropertySortItem>, nil]
    # @param search [SellApp::SearchUpsellOffersRequestApplicationJsonPropertySearch, nil]
    # @param includes [Array<SellApp::SearchUpsellOffersRequestApplicationJsonPropertyIncludesItem>, nil]
    # @param limit [Integer, nil] Number of items to return per page.
    # @param page [Integer, nil] Page number to return.
    # @param pagination [Boolean, nil] Set to false to return at most 100 matching items in one data array without pagination links or metadata.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkSearchUpsellOffersResponseValue200ApplicationJson]
    def search(
      filters: nil,
      sort: nil,
      search: nil,
      includes: nil,
      limit: 15,
      page: 1,
      pagination: true,
      request_options: {}
    )
      params = {
        'limit' => limit,
        'page' => page,
        'pagination' => pagination
      }.compact
      body = {
        'filters' => filters,
        'sort' => sort,
        'search' => search,
        'includes' => includes
      }.compact
      SellApp::Types::BaseModel.validate_value!(limit, {kind: :integer, minimum: 1, maximum: 100}, "$request.limit") unless limit.nil?
      SellApp::Types::BaseModel.validate_value!(page, {kind: :integer, minimum: 1}, "$request.page") unless page.nil?
      SellApp::Types::BaseModel.validate_value!(pagination, {kind: :boolean}, "$request.pagination") unless pagination.nil?
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkSearchUpsellOffersRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'searchUpsellOffers', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :post,
        path: '/v2/upsell-offers/search',
        auth: true,
        params: params,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkSearchUpsellOffersResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Retrieve an upsell offer
    # @param upsell_offer [Integer] The upsellOffer path parameter.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkGetUpsellOfferResponseValue200ApplicationJson]
    def get(
      upsell_offer:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(upsell_offer, {kind: :integer}, "$request.upsellOffer")
      request_options = request_options.merge(operation_id: 'getUpsellOffer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :get,
        path: "/v2/upsell-offers/#{SellApp::Util.encode_path(upsell_offer)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkGetUpsellOfferResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Update an upsell offer
    # @param upsell_offer [Integer] The upsellOffer path parameter.
    # @param name [String, nil]
    # @param description [String, nil]
    # @param is_active [Boolean, nil]
    # @param source_listing_id [Integer, nil]
    # @param source_variant_id [Integer, nil]
    # @param minimum_order_total_usd_cents [Integer, nil] Integer USD cents, for example 1000 for USD 10.00.
    # @param maximum_order_total_usd_cents [Integer, nil] Integer USD cents. When present, must be greater than or equal to minimum_order_total_usd_cents.
    # @param starts_at [String, nil]
    # @param ends_at [String, nil] Must be after or equal to starts_at.
    # @param available_for_days [Integer, nil]
    # @param max_accepts_per_customer [Integer, nil]
    # @param expected_version [Integer] Required optimistic concurrency token for updates. Use the version from the latest response; stale versions are rejected with 422.
    # @param items [Array<SellApp::ReplaceUpsellOfferRequestApplicationJsonPropertyItemsItem>, nil] Complete ordered target-item set. Target variant IDs must be unique and belong to their target product in this store.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkReplaceUpsellOfferResponseValue200ApplicationJson]
    def replace(
      upsell_offer:,
      expected_version:,
      name: nil,
      description: SellApp::OMIT,
      is_active: nil,
      source_listing_id: nil,
      source_variant_id: SellApp::OMIT,
      minimum_order_total_usd_cents: SellApp::OMIT,
      maximum_order_total_usd_cents: SellApp::OMIT,
      starts_at: SellApp::OMIT,
      ends_at: SellApp::OMIT,
      available_for_days: SellApp::OMIT,
      max_accepts_per_customer: SellApp::OMIT,
      items: nil,
      request_options: {}
    )
      body = {
        'name' => name,
        'is_active' => is_active,
        'source_listing_id' => source_listing_id,
        'expected_version' => expected_version,
        'items' => items
      }.compact
      body['description'] = description unless description.equal?(SellApp::OMIT)
      body['source_variant_id'] = source_variant_id unless source_variant_id.equal?(SellApp::OMIT)
      body['minimum_order_total_usd_cents'] = minimum_order_total_usd_cents unless minimum_order_total_usd_cents.equal?(SellApp::OMIT)
      body['maximum_order_total_usd_cents'] = maximum_order_total_usd_cents unless maximum_order_total_usd_cents.equal?(SellApp::OMIT)
      body['starts_at'] = starts_at unless starts_at.equal?(SellApp::OMIT)
      body['ends_at'] = ends_at unless ends_at.equal?(SellApp::OMIT)
      body['available_for_days'] = available_for_days unless available_for_days.equal?(SellApp::OMIT)
      body['max_accepts_per_customer'] = max_accepts_per_customer unless max_accepts_per_customer.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(upsell_offer, {kind: :integer}, "$request.upsellOffer")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkReplaceUpsellOfferRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'replaceUpsellOffer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :put,
        path: "/v2/upsell-offers/#{SellApp::Util.encode_path(upsell_offer)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkReplaceUpsellOfferResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Update an upsell offer
    # @param upsell_offer [Integer] The upsellOffer path parameter.
    # @param name [String, nil]
    # @param description [String, nil]
    # @param is_active [Boolean, nil]
    # @param source_listing_id [Integer, nil]
    # @param source_variant_id [Integer, nil]
    # @param minimum_order_total_usd_cents [Integer, nil] Integer USD cents, for example 1000 for USD 10.00.
    # @param maximum_order_total_usd_cents [Integer, nil] Integer USD cents. When present, must be greater than or equal to minimum_order_total_usd_cents.
    # @param starts_at [String, nil]
    # @param ends_at [String, nil] Must be after or equal to starts_at.
    # @param available_for_days [Integer, nil]
    # @param max_accepts_per_customer [Integer, nil]
    # @param expected_version [Integer] Required optimistic concurrency token for updates. Use the version from the latest response; stale versions are rejected with 422.
    # @param items [Array<SellApp::UpdateUpsellOfferRequestApplicationJsonPropertyItemsItem>, nil] Complete ordered target-item set. Target variant IDs must be unique and belong to their target product in this store.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkUpdateUpsellOfferResponseValue200ApplicationJson]
    def update(
      upsell_offer:,
      expected_version:,
      name: nil,
      description: SellApp::OMIT,
      is_active: nil,
      source_listing_id: nil,
      source_variant_id: SellApp::OMIT,
      minimum_order_total_usd_cents: SellApp::OMIT,
      maximum_order_total_usd_cents: SellApp::OMIT,
      starts_at: SellApp::OMIT,
      ends_at: SellApp::OMIT,
      available_for_days: SellApp::OMIT,
      max_accepts_per_customer: SellApp::OMIT,
      items: nil,
      request_options: {}
    )
      body = {
        'name' => name,
        'is_active' => is_active,
        'source_listing_id' => source_listing_id,
        'expected_version' => expected_version,
        'items' => items
      }.compact
      body['description'] = description unless description.equal?(SellApp::OMIT)
      body['source_variant_id'] = source_variant_id unless source_variant_id.equal?(SellApp::OMIT)
      body['minimum_order_total_usd_cents'] = minimum_order_total_usd_cents unless minimum_order_total_usd_cents.equal?(SellApp::OMIT)
      body['maximum_order_total_usd_cents'] = maximum_order_total_usd_cents unless maximum_order_total_usd_cents.equal?(SellApp::OMIT)
      body['starts_at'] = starts_at unless starts_at.equal?(SellApp::OMIT)
      body['ends_at'] = ends_at unless ends_at.equal?(SellApp::OMIT)
      body['available_for_days'] = available_for_days unless available_for_days.equal?(SellApp::OMIT)
      body['max_accepts_per_customer'] = max_accepts_per_customer unless max_accepts_per_customer.equal?(SellApp::OMIT)
      SellApp::Types::BaseModel.validate_value!(upsell_offer, {kind: :integer}, "$request.upsellOffer")
      SellApp::Types::BaseModel.validate_value!(body, {kind: :model, name: "SellApp::SdkUpdateUpsellOfferRequestApplicationJson"}, "$request.body")
      request_options = request_options.merge(operation_id: 'updateUpsellOffer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :patch,
        path: "/v2/upsell-offers/#{SellApp::Util.encode_path(upsell_offer)}",
        auth: true,
        body: body,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkUpdateUpsellOfferResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end

    # Delete an upsell offer
    # @param upsell_offer [Integer] The upsellOffer path parameter.
    # @param request_options [Hash] (see SellApp::Types::RequestOptions)
    # @return [SellApp::SdkDeleteUpsellOfferResponseValue200ApplicationJson]
    def delete(
      upsell_offer:,
      request_options: {}
    )
      SellApp::Types::BaseModel.validate_value!(upsell_offer, {kind: :integer}, "$request.upsellOffer")
      request_options = request_options.merge(operation_id: 'deleteUpsellOffer', credential_policy: {anonymous: false, apiKey: true, accessToken: true, customerSession: false, browserSession: false, clientBasic: false, apiKeyRequiresStore: false, apiKeyUsesStore: true, accessTokenRequiresStore: true}, retry_forbidden: false, idempotency_supported: false)
      response = @client.request(
        method: :delete,
        path: "/v2/upsell-offers/#{SellApp::Util.encode_path(upsell_offer)}",
        auth: true,
        request_options: request_options
      )
      value = begin
        result = SellApp::SdkDeleteUpsellOfferResponseValue200ApplicationJson.new(response.body)
        result.last_response = SellApp::Types::ApiResponse.new(http_status: response.code.to_i, http_headers: response.each_header.to_h, request_id: response["x-request-id"])
        result
      end
      @client.wrap_response(value, response, request_options)
    end
  end
end
