# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require "uri"
module SellApp
  module Util
    def self.encode_path(value); URI.encode_www_form_component(value.to_s); end
  end
end
