# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateRewardCouponTemplateResponseValue201ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      name: :name,
      type: :type,
      discount: :discount,
      store_wide: :store_wide,
      minimum_amount: :minimum_amount,
      maximum_discount_amount: :maximum_discount_amount,
      expires_at: :expires_at,
      expires_after_days: :expires_after_days,
      redemption_mode: :redemption_mode,
      is_active: :is_active,
      listing_ids: :listing_ids,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      name: {required: true, schema: {kind: :string}},
      type: {required: true, schema: {kind: :enum, values: ["PERCENTAGE", "AMOUNT"]}},
      discount: {required: true, schema: {kind: :string}},
      store_wide: {required: true, schema: {kind: :boolean}},
      minimum_amount: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      maximum_discount_amount: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      expires_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      expires_after_days: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1}}},
      redemption_mode: {required: true, schema: {kind: :enum, values: ["customer_locked", "shareable_once"]}},
      is_active: {required: true, schema: {kind: :boolean}},
      listing_ids: {required: false, schema: {kind: :array, items: {kind: :integer}}},
      created_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}},
      updated_at: {required: false, schema: {kind: :nullable, inner: {kind: :string, format: "date-time"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :name,
      :type,
      :discount,
      :store_wide,
      :minimum_amount,
      :maximum_discount_amount,
      :expires_at,
      :expires_after_days,
      :redemption_mode,
      :is_active,
      :listing_ids,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @name = hash[:name]
      @type = hash[:type]
      @discount = hash[:discount]
      @store_wide = hash[:store_wide]
      @minimum_amount = hash[:minimum_amount]
      @maximum_discount_amount = hash[:maximum_discount_amount]
      @expires_at = hash[:expires_at]
      @expires_after_days = hash[:expires_after_days]
      @redemption_mode = hash[:redemption_mode]
      @is_active = hash[:is_active]
      @listing_ids = hash[:listing_ids]
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
