# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class BatchCreateProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency < SellApp::Types::BaseModel
    HASH_ATTRS = {
      value: :value,
      interval: :interval
    }.freeze

    SCHEMA = {
      value: {required: true, schema: {kind: :integer}},
      interval: {required: true, schema: {kind: :string}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :value,
      :interval

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @value = hash[:value]
      @interval = hash[:interval]
    end
  end
end
