# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItemPropertyBulkDiscountItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      minimum_purchase_amount: :minimum_purchase_amount,
      discount_percentage: :discount_percentage
    }.freeze

    SCHEMA = {
      minimum_purchase_amount: {required: true, schema: {kind: :integer}},
      discount_percentage: {required: true, schema: {kind: :integer}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :minimum_purchase_amount,
      :discount_percentage

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @minimum_purchase_amount = hash[:minimum_purchase_amount]
      @discount_percentage = hash[:discount_percentage]
    end
  end
end
