# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  GetProductVariantResponseValue200ApplicationJsonPropertyData = BatchCreateProductVariantsResponseValue200ApplicationJsonPropertyDataItem
end
