# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkReleaseBookingHoldResponseValue200ApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      ok: :ok
    }.freeze

    SCHEMA = {
      ok: {required: true, schema: {kind: :boolean}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor :ok

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @ok = hash[:ok]
    end
  end
end
