# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkBatchCreateProductVariantsRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      resources: :resources
    }.freeze

    SCHEMA = {
      resources: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor :resources

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @resources = hash[:resources] ? hash[:resources].map { |item| item ? SellApp::BatchCreateProductVariantsRequestApplicationJsonPropertyResourcesItem.new(item) : nil } : nil
    end
  end
end
