# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  UpdateProductVariantPricingResponseValue200ApplicationJsonPropertyDataPropertyPricing = BatchCreateProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyPricing
end
