# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  UpdateProductVariantResponseValue200ApplicationJsonPropertyData = BatchCreateProductVariantsResponseValue200ApplicationJsonPropertyDataItem
end
