# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class AddOnsParentProductsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser")
  end

  def test_list_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/addons/1/parent-products(\?|\z)})
      .to_return(body: '{}', status: 200)
    result = @client.add_ons_parent_products.list(addon: 1)
    refute_nil result
  end

  def test_replace_returns_expected_result
    stub_request(:put, %r{\Ahttps://sell\.app/api/v2/addons/1/parent-products(\?|\z)})
      .to_return(body: '{"data":{"id":1,"store_id":1,"title":"stub","slug":"stub","description":"stub","visibility":"PUBLIC","type":"addon","is_draft":true,"is_discoverable":true,"parent_product_ids":[],"variants":[],"created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","deleted_at":"2024-01-01T00:00:00Z"}}', status: 200)
    result = @client.add_ons_parent_products.replace(addon: 1, resources: JSON.parse('[]'))
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :list, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/addons/1/parent-products(\?|\z)}, args: {addon: 1}},
    {name: :replace, verb: :put, url: %r{\Ahttps://sell\.app/api/v2/addons/1/parent-products(\?|\z)}, args: {addon: 1, resources: JSON.parse('[]')}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.add_ons_parent_products.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
