# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class ProductsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser")
  end

  def test_list_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/products(\?|\z)})
      .to_return(body: '{"data":[],"links":{"first":"stub","last":"stub","prev":"stub","next":"stub"},"meta":{"current_page":1,"from":1,"last_page":1,"links":[],"path":"stub","per_page":1,"to":1,"total":1}}', status: 200)
    result = @client.products.list()
    refute_nil result
  end

  def test_create_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/products(\?|\z)})
      .to_return(body: '{"data":{"id":1,"title":"stub","slug":"stub","description":"stub","images":[],"order":1,"visibility":"stub","delivery_text":"stub","additional_information":[],"other_settings":{"faq":[],"video_url":"stub","redirect_url":"stub","product_title":"stub","product_description":"stub"},"deleted_at":"2024-01-01T00:00:00Z","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"section_id":1,"section_order":1,"is_discoverable":true,"variants":[],"url":"stub"}}', status: 200)
    result = @client.products.create(title: 'stub', description: 'stub', visibility: 'PUBLIC')
    refute_nil result
  end

  def test_get_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)})
      .to_return(body: '{"data":{"id":1,"title":"stub","slug":"stub","description":"stub","images":[],"order":1,"visibility":"stub","delivery_text":"stub","additional_information":[],"other_settings":{"faq":[],"video_url":"stub","redirect_url":"stub","product_title":"stub","product_description":"stub"},"deleted_at":"2024-01-01T00:00:00Z","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"section_id":1,"section_order":1,"is_discoverable":true,"variants":[],"url":"stub"}}', status: 200)
    result = @client.products.get(product: 1)
    refute_nil result
  end

  def test_replace_returns_expected_result
    stub_request(:put, %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)})
      .to_return(body: '{"data":{"id":1,"title":"stub","slug":"stub","description":"stub","images":[],"order":1,"visibility":"stub","delivery_text":"stub","additional_information":[],"other_settings":{"faq":[],"video_url":"stub","redirect_url":"stub","product_title":"stub","product_description":"stub"},"deleted_at":"2024-01-01T00:00:00Z","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"section_id":1,"section_order":1,"is_discoverable":true,"variants":[],"url":"stub"}}', status: 200)
    result = @client.products.replace(product: 1)
    refute_nil result
  end

  def test_update_returns_expected_result
    stub_request(:patch, %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)})
      .to_return(body: '{"data":{"id":1,"title":"stub","slug":"stub","description":"stub","images":[],"order":1,"visibility":"stub","delivery_text":"stub","additional_information":[],"other_settings":{"faq":[],"video_url":"stub","redirect_url":"stub","product_title":"stub","product_description":"stub"},"deleted_at":"2024-01-01T00:00:00Z","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"section_id":1,"section_order":1,"is_discoverable":true,"variants":[],"url":"stub"}}', status: 200)
    result = @client.products.update(product: 1)
    refute_nil result
  end

  def test_delete_returns_expected_result
    stub_request(:delete, %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)})
      .to_return(body: '{"data":{"id":1,"title":"stub","slug":"stub","description":"stub","images":[],"order":1,"visibility":"stub","delivery_text":"stub","additional_information":[],"other_settings":{"faq":[],"video_url":"stub","redirect_url":"stub","product_title":"stub","product_description":"stub"},"deleted_at":"2024-01-01T00:00:00Z","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"section_id":1,"section_order":1,"is_discoverable":true,"variants":[],"url":"stub"}}', status: 200)
    result = @client.products.delete(product: 1)
    refute_nil result
  end

  def test_search_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/products/search(\?|\z)})
      .to_return(body: '{"data":[],"links":{},"meta":{}}', status: 200)
    result = @client.products.search()
    refute_nil result
  end

  def test_batch_create_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/products/batch(\?|\z)})
      .to_return(body: '{"data":[]}', status: 200)
    result = @client.products.batch_create(resources: JSON.parse('[]'))
    refute_nil result
  end

  def test_batch_update_returns_expected_result
    stub_request(:patch, %r{\Ahttps://sell\.app/api/v2/products/batch(\?|\z)})
      .to_return(body: '{"data":[]}', status: 200)
    result = @client.products.batch_update(resources: JSON.parse('{}'))
    refute_nil result
  end

  def test_batch_delete_returns_expected_result
    stub_request(:delete, %r{\Ahttps://sell\.app/api/v2/products/batch(\?|\z)})
      .to_return(body: '{"data":[]}', status: 200)
    result = @client.products.batch_delete(resources: JSON.parse('[1]'))
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :list, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/products(\?|\z)}},
    {name: :create, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/products(\?|\z)}, args: {title: 'stub', description: 'stub', visibility: 'PUBLIC'}},
    {name: :get, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)}, args: {product: 1}},
    {name: :replace, verb: :put, url: %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)}, args: {product: 1}},
    {name: :update, verb: :patch, url: %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)}, args: {product: 1}},
    {name: :delete, verb: :delete, url: %r{\Ahttps://sell\.app/api/v2/products/1(\?|\z)}, args: {product: 1}},
    {name: :search, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/products/search(\?|\z)}},
    {name: :batch_create, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/products/batch(\?|\z)}, args: {resources: JSON.parse('[]')}},
    {name: :batch_update, verb: :patch, url: %r{\Ahttps://sell\.app/api/v2/products/batch(\?|\z)}, args: {resources: JSON.parse('{}')}},
    {name: :batch_delete, verb: :delete, url: %r{\Ahttps://sell\.app/api/v2/products/batch(\?|\z)}, args: {resources: JSON.parse('[1]')}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.products.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
