# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class WalletTopupsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser")
  end

  def test_create_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/wallets/1/top-ups(\?|\z)})
      .to_return(body: '{"data":{"charge_id":1,"amount_cents":1,"currency":"USD","checkout_url":"https://example.com","payment_method":"AUTHNET","custom_payment_method_id":"11111111111111111111111111"}}', status: 200)
    result = @client.wallet_topups.create(customer: 1, amount_cents: 1, payment_method: 'AUTHNET')
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :create, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/wallets/1/top-ups(\?|\z)}, args: {customer: 1, amount_cents: 1, payment_method: 'AUTHNET'}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.wallet_topups.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
