# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class WalletSettingsModelRoundTripTest < Minitest::Test
  def test_get_wallet_settings_response_value_200_application_json_property_data_round_trip
    fixture = {
      "enabled" => true,
      "minimum_top_up_cents" => 1,
      "maximum_top_up_cents" => 1,
      "expiration_days" => 1,
      "payment_methods" => JSON.parse('[]'),
    }
    model = SellApp::GetWalletSettingsResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["enabled"], json[:enabled]
    assert_equal fixture["minimum_top_up_cents"], json[:minimum_top_up_cents]
    assert_equal fixture["maximum_top_up_cents"], json[:maximum_top_up_cents]
    assert_equal fixture["expiration_days"], json[:expiration_days]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_wallet_settings_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"enabled":true,"minimum_top_up_cents":1,"maximum_top_up_cents":1,"expiration_days":1,"payment_methods":[]}'),
    }
    model = SellApp::SdkGetWalletSettingsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_replace_wallet_settings_request_application_json_round_trip
    fixture = {
      "enabled" => true,
      "minimum_top_up_cents" => 1,
      "maximum_top_up_cents" => 1,
      "expiration_days" => 1,
      "payment_methods" => JSON.parse('[]'),
    }
    model = SellApp::SdkReplaceWalletSettingsRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["enabled"], json[:enabled]
    assert_equal fixture["minimum_top_up_cents"], json[:minimum_top_up_cents]
    assert_equal fixture["maximum_top_up_cents"], json[:maximum_top_up_cents]
    assert_equal fixture["expiration_days"], json[:expiration_days]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_replace_wallet_settings_response_value_200_application_4e48057acb790584_round_trip
    fixture = {
      "enabled" => true,
      "minimum_top_up_cents" => 1,
      "maximum_top_up_cents" => 1,
      "expiration_days" => 1,
      "payment_methods" => JSON.parse('[]'),
    }
    model = SellApp::ReplaceWalletSettingsResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["enabled"], json[:enabled]
    assert_equal fixture["minimum_top_up_cents"], json[:minimum_top_up_cents]
    assert_equal fixture["maximum_top_up_cents"], json[:maximum_top_up_cents]
    assert_equal fixture["expiration_days"], json[:expiration_days]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_replace_wallet_settings_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"enabled":true,"minimum_top_up_cents":1,"maximum_top_up_cents":1,"expiration_days":1,"payment_methods":[]}'),
    }
    model = SellApp::SdkReplaceWalletSettingsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_customer_wallets_response_value_200_application_js_4f5c47a1a0cf2eee_round_trip
    fixture = {
      "id" => 1,
      "customer_id" => 1,
      "customer_email" => 'sdk@example.com',
      "balance_cents" => 0,
      "held_cents" => 0,
      "available_cents" => 0,
      "status" => 'active',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["customer_id"], json[:customer_id]
    assert_equal fixture["balance_cents"], json[:balance_cents]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_list_customer_wallets_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
      "links" => JSON.parse('{"first":"stub","last":"stub","prev":"stub","next":"stub"}'),
      "meta" => JSON.parse('{"current_page":1,"from":1,"last_page":1,"links":[],"path":"stub","per_page":1,"to":1,"total":1}'),
    }
    model = SellApp::SdkListCustomerWalletsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_customer_wallet_response_value_200_application_json_property_data_round_trip
    fixture = {
      "id" => 1,
      "customer_id" => 1,
      "customer_email" => 'sdk@example.com',
      "balance_cents" => 0,
      "held_cents" => 0,
      "available_cents" => 0,
      "status" => 'active',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::GetCustomerWalletResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["customer_id"], json[:customer_id]
    assert_equal fixture["balance_cents"], json[:balance_cents]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_customer_wallet_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"customer_id":1,"balance_cents":0,"status":"active"}'),
    }
    model = SellApp::SdkGetCustomerWalletResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_adjust_customer_wallet_request_application_json_round_trip
    fixture = {
      "amount_cents" => -999999999999,
      "idempotency_key" => 'stub',
      "note" => 'stub',
    }
    model = SellApp::SdkAdjustCustomerWalletRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["amount_cents"], json[:amount_cents]
    assert_equal fixture["idempotency_key"], json[:idempotency_key]
    assert_equal fixture["note"], json[:note]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_adjust_customer_wallet_response_value_200_application_json_property_data_round_trip
    fixture = {
      "id" => 1,
      "wallet_id" => 1,
      "type" => 'TOP_UP',
      "amount_cents" => -999999999999,
      "currency_at_source" => 'stub',
      "exchange_rate_to_usd" => 'stub',
      "order_id" => 1,
      "charge_id" => 1,
      "reverses_entry_id" => 1,
      "expired_at" => '2024-01-01T00:00:00Z',
      "balance_after_cents" => 0,
      "note" => 'stub',
      "idempotency_key" => 'stub',
      "expires_at" => '2024-01-01T00:00:00Z',
      "created_by_user_id" => 1,
      "created_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::AdjustCustomerWalletResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["wallet_id"], json[:wallet_id]
    assert_equal fixture["amount_cents"], json[:amount_cents]
    assert_equal fixture["balance_after_cents"], json[:balance_after_cents]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_adjust_customer_wallet_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"wallet_id":1,"type":"TOP_UP","amount_cents":-999999999999,"balance_after_cents":0}'),
    }
    model = SellApp::SdkAdjustCustomerWalletResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_update_customer_wallet_status_request_application_json_round_trip
    fixture = {
      "status" => 'active',
    }
    model = SellApp::SdkUpdateCustomerWalletStatusRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_customer_wallet_status_response_value_200_applic_645f9a571650c598_round_trip
    fixture = {
      "id" => 1,
      "customer_id" => 1,
      "customer_email" => 'sdk@example.com',
      "balance_cents" => 0,
      "held_cents" => 0,
      "available_cents" => 0,
      "status" => 'active',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::UpdateCustomerWalletStatusResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["customer_id"], json[:customer_id]
    assert_equal fixture["balance_cents"], json[:balance_cents]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_update_customer_wallet_status_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"customer_id":1,"balance_cents":0,"status":"active"}'),
    }
    model = SellApp::SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_wallet_transactions_response_value_200_application_6a2503c82e59bccd_round_trip
    fixture = {
      "id" => 1,
      "wallet_id" => 1,
      "type" => 'TOP_UP',
      "amount_cents" => -999999999999,
      "currency_at_source" => 'stub',
      "exchange_rate_to_usd" => 'stub',
      "order_id" => 1,
      "charge_id" => 1,
      "reverses_entry_id" => 1,
      "expired_at" => '2024-01-01T00:00:00Z',
      "balance_after_cents" => 0,
      "note" => 'stub',
      "idempotency_key" => 'stub',
      "expires_at" => '2024-01-01T00:00:00Z',
      "created_by_user_id" => 1,
      "created_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::ListWalletTransactionsResponseValue200ApplicationJsonPropertyDataItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["wallet_id"], json[:wallet_id]
    assert_equal fixture["amount_cents"], json[:amount_cents]
    assert_equal fixture["balance_after_cents"], json[:balance_after_cents]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_list_wallet_transactions_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
      "links" => JSON.parse('{"first":"stub","last":"stub","prev":"stub","next":"stub"}'),
      "meta" => JSON.parse('{"current_page":1,"from":1,"last_page":1,"links":[],"path":"stub","per_page":1,"to":1,"total":1}'),
    }
    model = SellApp::SdkListWalletTransactionsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_create_wallet_top_up_request_application_json_round_trip
    fixture = {
      "amount_cents" => 1,
      "payment_method" => 'AUTHNET',
      "custom_payment_method_id" => '11111111111111111111111111',
    }
    model = SellApp::SdkCreateWalletTopUpRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["amount_cents"], json[:amount_cents]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_create_wallet_top_up_response_value_201_application_json_property_data_round_trip
    fixture = {
      "charge_id" => 1,
      "amount_cents" => 1,
      "currency" => 'USD',
      "checkout_url" => 'https://example.com',
      "payment_method" => 'AUTHNET',
      "custom_payment_method_id" => '11111111111111111111111111',
    }
    model = SellApp::CreateWalletTopUpResponseValue201ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["charge_id"], json[:charge_id]
    assert_equal fixture["amount_cents"], json[:amount_cents]
    assert_equal fixture["checkout_url"], json[:checkout_url]
    assert_equal fixture["custom_payment_method_id"], json[:custom_payment_method_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_create_wallet_top_up_response_value_201_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"charge_id":1,"amount_cents":1,"currency":"USD","checkout_url":"https://example.com","payment_method":"AUTHNET","custom_payment_method_id":"11111111111111111111111111"}'),
    }
    model = SellApp::SdkCreateWalletTopUpResponseValue201ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
