# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class OAuthTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser")
  end

  def test_get_oauth_authorization_server_metadata_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/\.well-known/oauth-authorization-server(\?|\z)})
      .to_return(body: '{"issuer":"https://example.com","authorization_endpoint":"https://example.com","token_endpoint":"https://example.com","revocation_endpoint":"https://example.com","response_types_supported":[],"grant_types_supported":[],"code_challenge_methods_supported":[],"token_endpoint_auth_methods_supported":[],"revocation_endpoint_auth_methods_supported":[],"scopes_supported":[]}', status: 200)
    result = @client.oauth.get_oauth_authorization_server_metadata()
    refute_nil result
  end

  def test_get_oauth_authorization_request_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/oauth/authorize(\?|\z)})
      .to_return(body: '"stub"', status: 200)
    result = @client.oauth.get_oauth_authorization_request(response_type: 'code', client_id: '00000000-0000-4000-8000-000000000000', redirect_uri: 'https://example.com', state: 'stub', code_challenge: 'stubxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', code_challenge_method: 'S256')
    refute_nil result
  end

  def test_approve_oauth_authorization_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/oauth/authorize(\?|\z)})
      .to_return(body: '{}', status: 200)
    result = @client.oauth.approve_oauth_authorization(auth_token: 'stub', client_id: '00000000-0000-4000-8000-000000000000', state: 'stub', token: 'stub')
    refute_nil result
  end

  def test_deny_oauth_authorization_returns_expected_result
    stub_request(:delete, %r{\Ahttps://sell\.app/oauth/authorize(\?|\z)})
      .to_return(body: '{}', status: 200)
    result = @client.oauth.deny_oauth_authorization(auth_token: 'stub', token: 'stub')
    refute_nil result
  end

  def test_exchange_oauth_token_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/oauth/token(\?|\z)})
      .to_return(body: '{"token_type":"Bearer","expires_in":3600,"access_token":"stub","refresh_token":"stub"}', status: 200)
    result = @client.oauth.exchange_oauth_token(grant_type: 'authorization_code', code: 'stub', redirect_uri: 'https://example.com', code_verifier: 'stubxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
    refute_nil result
  end

  def test_revoke_oauth_token_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/oauth/revoke(\?|\z)})
      .to_return(body: '[]', status: 200)
    result = @client.oauth.revoke_oauth_token(token: 'stub')
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :get_oauth_authorization_server_metadata, verb: :get, url: %r{\Ahttps://sell\.app/\.well-known/oauth-authorization-server(\?|\z)}},
    {name: :get_oauth_authorization_request, verb: :get, url: %r{\Ahttps://sell\.app/oauth/authorize(\?|\z)}, args: {response_type: 'code', client_id: '00000000-0000-4000-8000-000000000000', redirect_uri: 'https://example.com', state: 'stub', code_challenge: 'stubxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', code_challenge_method: 'S256'}},
    {name: :approve_oauth_authorization, verb: :post, url: %r{\Ahttps://sell\.app/oauth/authorize(\?|\z)}, args: {auth_token: 'stub', client_id: '00000000-0000-4000-8000-000000000000', state: 'stub', token: 'stub'}},
    {name: :deny_oauth_authorization, verb: :delete, url: %r{\Ahttps://sell\.app/oauth/authorize(\?|\z)}, args: {auth_token: 'stub', token: 'stub'}},
    {name: :exchange_oauth_token, verb: :post, url: %r{\Ahttps://sell\.app/oauth/token(\?|\z)}, args: {grant_type: 'authorization_code', code: 'stub', redirect_uri: 'https://example.com', code_verifier: 'stubxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}},
    {name: :revoke_oauth_token, verb: :post, url: %r{\Ahttps://sell\.app/oauth/revoke(\?|\z)}, args: {token: 'stub'}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.oauth.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
