# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class RuntimeContractTest < Minitest::Test
  FakeResponse = Struct.new(:code, :body, :headers) do
    def [](name); (headers || {})[name.downcase] || (headers || {})[name]; end
    def each_header(&block); (headers || {}).each(&block); end
  end

  class QueueTransport
    attr_reader :calls
    def initialize(*outcomes); @outcomes, @calls = outcomes, []; end

    def call(**request)
      @calls << request
      outcome = @outcomes.shift
      raise outcome if outcome.is_a?(Exception)
      outcome
    end
  end

  def client(transport, **options)
    SellApp::Client.new(
      api_key: 'key', store: 'store', transport: transport,
      sleeper: ->(_delay) {}, random: Object.new.tap { |value| def value.rand; 0.0; end },
      **options
    )
  end

  def test_injected_transport_receives_credentials
    transport = QueueTransport.new(FakeResponse.new('200', '{}', {}))
    client(transport).request(method: :get, path: '/local', auth: true)
    assert_equal 'Bearer key', transport.calls.first[:headers]['Authorization']
    assert_equal 'store', transport.calls.first[:headers]['X-STORE']
  end

  def test_zero_disables_retries
    transport = QueueTransport.new(FakeResponse.new('503', '{}', {}))
    assert_raises(SellApp::ApiError) do
      client(transport).request(method: :get, path: '/local', auth: true, request_options: {max_retries: 0})
    end
    assert_equal 1, transport.calls.length
  end

  def test_retry_after_and_timeout_are_retried_for_safe_methods
    transport = QueueTransport.new(
      Net::ReadTimeout.new('timeout'),
      FakeResponse.new('503', '{}', {'retry-after' => '0'}),
      FakeResponse.new('200', '{}', {})
    )
    result = client(transport).request(method: :get, path: '/local', auth: true, request_options: {max_retries: 2})
    assert_equal '200', result.code
    assert_equal 3, transport.calls.length
  end

  def test_non_idempotent_requests_require_an_idempotency_key_to_retry
    unsafe = QueueTransport.new(FakeResponse.new('503', '{}', {}), FakeResponse.new('200', '{}', {}))
    assert_raises(SellApp::ApiError) do
      client(unsafe).request(method: :post, path: '/local', auth: true, body: {}, request_options: {max_retries: 1})
    end
    assert_equal 1, unsafe.calls.length

    keyed_but_undeclared = QueueTransport.new(FakeResponse.new('503', '{}', {}), FakeResponse.new('200', '{}', {}))
    assert_raises(SellApp::ApiError) do
      client(keyed_but_undeclared).request(
        method: :post, path: '/local', auth: true, body: {},
        request_options: {max_retries: 1, idempotency_key: 'idem-12345678'}
      )
    end
    assert_equal 1, keyed_but_undeclared.calls.length
  end

  def test_auto_pagination_continues_through_empty_pages
    first = FakeResponse.new('200', '{"data":[],"list_metadata":{"after":"next"}}', {})
    second = FakeResponse.new('200', '{"data":[1],"list_metadata":{}}', {})
    page = SellApp::Types::ListStruct.from_response(
      first,
      fetch_next: ->(_token) { SellApp::Types::ListStruct.from_response(second) }
    )
    assert_equal [1], page.to_a
  end
end
