# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class SubscriptionsModelRoundTripTest < Minitest::Test
  def test_scalar_metadata_value_round_trip
    model = SellApp::ScalarMetadataValue.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_sdk_cancel_subscription_request_application_json_round_trip
    fixture = {
      "cancel_at_period_end" => true,
      "refund_last_payment" => true,
      "pro_rated_refund" => true,
      "idempotency_key" => 'stub',
    }
    model = SellApp::SdkCancelSubscriptionRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["cancel_at_period_end"], json[:cancel_at_period_end]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_subscription_response_value_200_application_json_property_data_round_trip
    fixture = {
      "id" => 1,
      "invoice_id" => 1,
      "provider" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "customer_email" => 'stub',
      "status" => 'stub',
      "current_period_start" => '2024-01-01T00:00:00Z',
      "current_period_end" => '2024-01-01T00:00:00Z',
      "cancel_at_period_end" => true,
      "cancellation_in_progress" => true,
      "store_id" => 1,
      "product_variant_id" => 1,
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::CancelSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["invoice_id"], json[:invoice_id]
    assert_equal fixture["provider"], json[:provider]
    assert_equal fixture["subscription_id"], json[:subscription_id]
    assert_equal fixture["customer_id"], json[:customer_id]
    assert_equal fixture["customer_email"], json[:customer_email]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["current_period_start"], json[:current_period_start]
    assert_equal fixture["current_period_end"], json[:current_period_end]
    assert_equal fixture["cancel_at_period_end"], json[:cancel_at_period_end]
    assert_equal fixture["cancellation_in_progress"], json[:cancellation_in_progress]
    assert_equal fixture["store_id"], json[:store_id]
    assert_equal fixture["product_variant_id"], json[:product_variant_id]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"invoice_id":1,"provider":"stub","subscription_id":"stub","customer_id":"stub","customer_email":"stub","status":"stub","current_period_start":"2024-01-01T00:00:00Z","current_period_end":"2024-01-01T00:00:00Z","cancel_at_period_end":true,"cancellation_in_progress":true,"store_id":1,"product_variant_id":1,"created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"}'),
      "message" => 'stub',
    }
    model = SellApp::SdkCancelSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_subscription_capabilities_response_value_200_applic_1761c493e9598500_round_trip
    fixture = {
      "status" => 'available',
      "customer_reason" => 'stub',
      "seller_reason" => 'stub',
    }
    model = SellApp::GetSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyDataPropertyCapabilitiesMapValue.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_subscription_capabilities_response_value_200_applic_2a33e1591398bea6_round_trip
    model = SellApp::GetSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyDataPropertyCapabilities.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_get_subscription_capabilities_response_value_200_applic_aed457f27d662fac_round_trip
    fixture = {
      "id" => 1,
      "subscription_id" => 'stub',
      "capabilities" => JSON.parse('{}'),
    }
    model = SellApp::GetSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["subscription_id"], json[:subscription_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_subscription_capabilities_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"subscription_id":"stub","capabilities":{}}'),
    }
    model = SellApp::SdkGetSubscriptionCapabilitiesResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_subscription_at_period_end_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "reason" => 'stub',
    }
    model = SellApp::SdkCancelSubscriptionAtPeriodEndRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_subscription_at_period_end_response_value_200_ap_6409adac3c0f0072_round_trip
    fixture = {
      "id" => 1,
      "product_subscription_id" => 1,
      "subscription_id" => 'stub',
      "action" => 'pause',
      "status" => 'pending',
      "provider" => 'stub',
      "customer_message" => 'stub',
      "confirmed_at" => '2024-01-01T00:00:00Z',
      "failed_at" => '2024-01-01T00:00:00Z',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::CancelSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_subscription_at_period_end_response_value_20_d3022353fde1bbb5_round_trip
    fixture = {
      "data" => JSON.parse('{}'),
      "message" => 'stub',
    }
    model = SellApp::SdkCancelSubscriptionAtPeriodEndResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_subscription_immediately_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "reason" => 'stub',
      "refund_last_payment" => true,
      "pro_rated_refund" => true,
    }
    model = SellApp::SdkCancelSubscriptionImmediatelyRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_subscription_immediately_response_value_200_appl_e9e78022e05c4ccb_round_trip
    fixture = {
      "id" => 1,
      "product_subscription_id" => 1,
      "subscription_id" => 'stub',
      "action" => 'pause',
      "status" => 'pending',
      "provider" => 'stub',
      "customer_message" => 'stub',
      "confirmed_at" => '2024-01-01T00:00:00Z',
      "failed_at" => '2024-01-01T00:00:00Z',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::CancelSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_subscription_immediately_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{}'),
      "message" => 'stub',
    }
    model = SellApp::SdkCancelSubscriptionImmediatelyResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_pause_subscription_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "resume_at" => '2024-01-01T00:00:00Z',
      "reason" => 'stub',
    }
    model = SellApp::SdkPauseSubscriptionRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_pause_subscription_response_value_200_application_json_property_data_round_trip
    fixture = {
      "id" => 1,
      "product_subscription_id" => 1,
      "subscription_id" => 'stub',
      "action" => 'pause',
      "status" => 'pending',
      "provider" => 'stub',
      "customer_message" => 'stub',
      "confirmed_at" => '2024-01-01T00:00:00Z',
      "failed_at" => '2024-01-01T00:00:00Z',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::PauseSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_pause_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{}'),
      "message" => 'stub',
    }
    model = SellApp::SdkPauseSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_resume_subscription_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
    }
    model = SellApp::SdkResumeSubscriptionRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_resume_subscription_response_value_200_application_json_property_data_round_trip
    fixture = {
      "id" => 1,
      "product_subscription_id" => 1,
      "subscription_id" => 'stub',
      "action" => 'pause',
      "status" => 'pending',
      "provider" => 'stub',
      "customer_message" => 'stub',
      "confirmed_at" => '2024-01-01T00:00:00Z',
      "failed_at" => '2024-01-01T00:00:00Z',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::ResumeSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_resume_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{}'),
      "message" => 'stub',
    }
    model = SellApp::SdkResumeSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_update_subscription_payment_method_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
    }
    model = SellApp::SdkUpdateSubscriptionPaymentMethodRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_subscription_plan_change_request_application_js_ffccf2299d201d20_round_trip
    model = SellApp::PreviewSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_sdk_preview_subscription_plan_change_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "target_variant_id" => 1,
      "effective_timing" => 'immediate',
      "proration_behavior" => 'invoice_now',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::SdkPreviewSubscriptionPlanChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["target_variant_id"], json[:target_variant_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_subscription_plan_change_request_application_js_852551eec6afce67_round_trip
    model = SellApp::ConfirmSubscriptionPlanChangeRequestApplicationJsonPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_sdk_confirm_subscription_plan_change_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "target_variant_id" => 1,
      "preview_token" => 'stub',
      "effective_timing" => 'immediate',
      "proration_behavior" => 'invoice_now',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::SdkConfirmSubscriptionPlanChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["target_variant_id"], json[:target_variant_id]
    assert_equal fixture["preview_token"], json[:preview_token]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_subscription_renewal_date_change_request_applic_94be8bd1a037998d_round_trip
    model = SellApp::PreviewSubscriptionRenewalDateChangeRequestApplicationJsonPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_sdk_preview_subscription_renewal_date_change_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "renewal_date" => '2024-01-01T00:00:00Z',
      "reason" => 'stub',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::SdkPreviewSubscriptionRenewalDateChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["renewal_date"], json[:renewal_date]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_subscription_renewal_date_change_response_value_dfb6b3898a9d8744_round_trip
    model = SellApp::PreviewSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyDataPropertyPreviewPayload.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_preview_subscription_renewal_date_change_response_value_2b95ff3df9c97848_round_trip
    model = SellApp::PreviewSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyDataPropertyRequestPayload.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_preview_subscription_renewal_date_change_response_value_24021372b8edb1de_round_trip
    fixture = {
      "preview_token" => 'stub',
      "expires_at" => '2024-01-01T00:00:00Z',
      "preview_payload" => JSON.parse('{}'),
      "request_payload" => JSON.parse('{}'),
      "customer_message" => 'stub',
      "seller_message" => 'stub',
    }
    model = SellApp::PreviewSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_preview_subscription_renewal_date_change_response_v_ea3023ac27ddc4aa_round_trip
    fixture = {
      "data" => JSON.parse('{}'),
      "message" => 'stub',
    }
    model = SellApp::SdkPreviewSubscriptionRenewalDateChangeResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_subscription_renewal_date_change_request_applic_a01e7fdfcd57cefb_round_trip
    model = SellApp::ConfirmSubscriptionRenewalDateChangeRequestApplicationJsonPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_sdk_confirm_subscription_renewal_date_change_request_application_json_round_trip
    fixture = {
      "idempotency_key" => 'stub',
      "renewal_date" => '2024-01-01T00:00:00Z',
      "preview_token" => 'stub',
      "reason" => 'stub',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::SdkConfirmSubscriptionRenewalDateChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["renewal_date"], json[:renewal_date]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_subscription_renewal_date_change_response_value_003754f9ed1da158_round_trip
    fixture = {
      "id" => 1,
      "product_subscription_id" => 1,
      "subscription_id" => 'stub',
      "action" => 'pause',
      "status" => 'pending',
      "provider" => 'stub',
      "customer_message" => 'stub',
      "confirmed_at" => '2024-01-01T00:00:00Z',
      "failed_at" => '2024-01-01T00:00:00Z',
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::ConfirmSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_confirm_subscription_renewal_date_change_response_v_e082aac5f2266713_round_trip
    fixture = {
      "data" => JSON.parse('{}'),
      "message" => 'stub',
    }
    model = SellApp::SdkConfirmSubscriptionRenewalDateChangeResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["message"], json[:message]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_subscriptions_response_value_200_application_json_5d2c3694b34cc2c9_round_trip
    model = SellApp::ListSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_list_subscriptions_response_value_200_application_json_ef5a64ce42a89897_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::ListSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_subscriptions_response_value_200_application_json_5543a884272391eb_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::ListSubscriptionsResponseValue200ApplicationJsonPropertyDataItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_list_subscriptions_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
      "links" => JSON.parse('{"first":"stub","last":"stub","prev":"stub","next":"stub"}'),
      "meta" => JSON.parse('{"current_page":1,"from":1,"last_page":1,"links":[],"path":"stub","per_page":1,"to":1,"total":1}'),
    }
    model = SellApp::SdkListSubscriptionsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_search_subscriptions_request_application_json_round_trip
    fixture = {
      "search" => 'stub',
      "status" => 'stub',
    }
    model = SellApp::SdkSearchSubscriptionsRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_search_subscriptions_response_value_200_application_jso_7acae8465bf50921_round_trip
    model = SellApp::SearchSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_search_subscriptions_response_value_200_application_jso_ef42956bab18d4ee_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::SearchSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_search_subscriptions_response_value_200_application_jso_458e9002411933f6_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::SearchSubscriptionsResponseValue200ApplicationJsonPropertyDataItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_search_subscriptions_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
      "links" => JSON.parse('{"first":"stub","last":"stub","prev":"stub","next":"stub"}'),
      "meta" => JSON.parse('{"current_page":1,"from":1,"last_page":1,"links":[],"path":"stub","per_page":1,"to":1,"total":1}'),
    }
    model = SellApp::SdkSearchSubscriptionsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_subscription_response_value_200_application_json_pr_fd726601caff080f_round_trip
    model = SellApp::GetSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_get_subscription_response_value_200_application_json_pr_02d4ff7e080fa2c4_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::GetSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_subscription_response_value_200_application_json_property_data_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::GetSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkGetSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
