# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class OAuthManagementTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser", access_token: "test_access_token")
  end

  def test_get_oauth_installation_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/oauth/installation(\?|\z)})
      .to_return(body: '{"data":{"id":"stub","client_id":"00000000-0000-4000-8000-000000000000","grant_model":"account","scopes":[],"created_at":"2024-01-01T00:00:00Z"}}', status: 200)
    result = @client.oauth_management.get_oauth_installation()
    refute_nil result
  end

  def test_delete_oauth_installation_returns_expected_result
    stub_request(:delete, %r{\Ahttps://sell\.app/api/v2/oauth/installation(\?|\z)})
      .to_return(body: '{}', status: 200)
    result = @client.oauth_management.delete_oauth_installation()
    assert_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :get_oauth_installation, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/oauth/installation(\?|\z)}},
    {name: :delete_oauth_installation, verb: :delete, url: %r{\Ahttps://sell\.app/api/v2/oauth/installation(\?|\z)}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.oauth_management.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
