# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class InvoicesTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser")
  end

  def test_list_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/invoices(\?|\z)})
      .to_return(body: '{"data":[],"links":{},"meta":{}}', status: 200)
    result = @client.invoices.list()
    refute_nil result
  end

  def test_create_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices(\?|\z)})
      .to_return(body: '{"data":{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"checkout":"stub","customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"}}}}', status: 200)
    result = @client.invoices.create(customer_email: 'sdk@example.com', payment_method: 'AUTHNET', product_variants: JSON.parse('{}'))
    refute_nil result
  end

  def test_search_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices/search(\?|\z)})
      .to_return(body: '{"data":[],"links":{},"meta":{}}', status: 200)
    result = @client.invoices.search()
    refute_nil result
  end

  def test_get_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/invoices/1(\?|\z)})
      .to_return(body: '{"data":{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]}}', status: 200)
    result = @client.invoices.get(invoice: 1)
    refute_nil result
  end

  def test_go_to_checkout_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices/1/checkout(\?|\z)})
      .to_return(body: '{"message":"stub","invoice":{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]}}', status: 200)
    result = @client.invoices.go_to_checkout(invoice: 1)
    refute_nil result
  end

  def test_get_deliverables_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/invoices/1/deliverables(\?|\z)})
      .to_return(body: '{"data":[]}', status: 200)
    result = @client.invoices.get_deliverables(invoice: 1)
    refute_nil result
  end

  def test_mark_completed_returns_expected_result
    stub_request(:patch, %r{\Ahttps://sell\.app/api/v2/invoices/1/mark-completed(\?|\z)})
      .to_return(body: '{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]}', status: 200)
    result = @client.invoices.mark_completed(invoice: 1)
    refute_nil result
  end

  def test_mark_voided_returns_expected_result
    stub_request(:patch, %r{\Ahttps://sell\.app/api/v2/invoices/1/mark-voided(\?|\z)})
      .to_return(body: '{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]}', status: 200)
    result = @client.invoices.mark_voided(invoice: 1)
    refute_nil result
  end

  def test_issue_replacement_returns_expected_result
    stub_request(:patch, %r{\Ahttps://sell\.app/api/v2/invoices/1/issue-replacement(\?|\z)})
      .to_return(body: '{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]}', status: 200)
    result = @client.invoices.issue_replacement(invoice: 1, product_variants: JSON.parse('{}'))
    refute_nil result
  end

  def test_update_status_returns_expected_result
    stub_request(:patch, %r{\Ahttps://sell\.app/api/v2/invoices/1/status(\?|\z)})
      .to_return(body: '{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]}', status: 200)
    result = @client.invoices.update_status(invoice: 1, status: 'COMPLETED')
    refute_nil result
  end

  def test_create_refund_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices/1/refunds(\?|\z)})
      .to_return(body: '{"data":{"invoice":{"id":1,"payment":{"fee":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"gateway":{"data":{},"type":"stub"},"subtotal":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"expires_at":"2024-01-01T00:00:00Z","full_price":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}},"original_amount":{"base":"stub","currency":"stub","units":1,"vat":1,"total":{"exclusive":"stub","inclusive":"stub"}}},"status":{"history":[],"status":{"setAt":"2024-01-01T00:00:00Z","status":"stub","updatedAt":"2024-01-01T00:00:00Z"}},"webhooks":[],"feedback":"stub","created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z","store_id":1,"coupon_id":1,"subscription_id":1,"customer_information":{"id":1,"email":"stub","country":"stub","location":"stub","ip":"stub","proxied":true,"browser_agent":"stub","vat":{"amount":"stub","country":"stub"},"discord_data":{},"billing_details":{}},"product_variants":[]},"refund":{"status":"pending","provider":"stub","provider_refund_id":"stub","amount_cents":1,"currency":"stub"}}}', status: 200)
    result = @client.invoices.create_refund(invoice: 1)
    refute_nil result
  end

  def test_retry_fulfillment_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices/1/fulfillment-retries(\?|\z)})
      .to_return(body: '{"data":{"effects_reset":1}}', status: 200)
    result = @client.invoices.retry_fulfillment(invoice: 1)
    refute_nil result
  end

  def test_retry_dynamic_delivery_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices/1/dynamic-delivery-retries(\?|\z)})
      .to_return(body: '{"data":{"queued":true}}', status: 200)
    result = @client.invoices.retry_dynamic_delivery(invoice: 1, delivered_product_id: 1)
    refute_nil result
  end

  def test_notify_fulfillment_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/invoices/1/fulfillment-notifications(\?|\z)})
      .to_return(body: '{"data":{"notifications_sent":1}}', status: 200)
    result = @client.invoices.notify_fulfillment(invoice: 1)
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :list, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/invoices(\?|\z)}},
    {name: :create, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices(\?|\z)}, args: {customer_email: 'sdk@example.com', payment_method: 'AUTHNET', product_variants: JSON.parse('{}')}},
    {name: :search, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices/search(\?|\z)}},
    {name: :get, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/invoices/1(\?|\z)}, args: {invoice: 1}},
    {name: :go_to_checkout, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/checkout(\?|\z)}, args: {invoice: 1}},
    {name: :get_deliverables, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/deliverables(\?|\z)}, args: {invoice: 1}},
    {name: :mark_completed, verb: :patch, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/mark-completed(\?|\z)}, args: {invoice: 1}},
    {name: :mark_voided, verb: :patch, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/mark-voided(\?|\z)}, args: {invoice: 1}},
    {name: :issue_replacement, verb: :patch, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/issue-replacement(\?|\z)}, args: {invoice: 1, product_variants: JSON.parse('{}')}},
    {name: :update_status, verb: :patch, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/status(\?|\z)}, args: {invoice: 1, status: 'COMPLETED'}},
    {name: :create_refund, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/refunds(\?|\z)}, args: {invoice: 1}},
    {name: :retry_fulfillment, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/fulfillment-retries(\?|\z)}, args: {invoice: 1}},
    {name: :retry_dynamic_delivery, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/dynamic-delivery-retries(\?|\z)}, args: {invoice: 1, delivered_product_id: 1}},
    {name: :notify_fulfillment, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/invoices/1/fulfillment-notifications(\?|\z)}, args: {invoice: 1}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.invoices.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
