# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class RewardGrantsTest < Minitest::Test
  include FixtureHelper

  def setup
    @client = SellApp::Client.new(api_key: "sk_test_123", store: "store_test_123", customer_session: "test_customer_session", browser_session: "session=test_browser")
  end

  def test_list_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/reward-grants(\?|\z)})
      .to_return(body: '{}', status: 200)
    result = @client.reward_grants.list()
    refute_nil result
  end

  def test_issue_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/reward-grants(\?|\z)})
      .to_return(body: '{"data":{"id":1,"reward_rule_id":1,"customer_id":1,"trigger_type":"PURCHASE_COUNT","trigger_value":1,"trigger_threshold":1,"outputs":[]}}', status: 200)
    result = @client.reward_grants.issue(reward_rule_id: 1, customer_id: 1)
    refute_nil result
  end

  def test_search_returns_expected_result
    stub_request(:post, %r{\Ahttps://sell\.app/api/v2/reward-grants/search(\?|\z)})
      .to_return(body: '{}', status: 200)
    result = @client.reward_grants.search()
    refute_nil result
  end

  def test_get_returns_expected_result
    stub_request(:get, %r{\Ahttps://sell\.app/api/v2/reward-grants/1(\?|\z)})
      .to_return(body: '{"data":{"id":1,"reward_rule_id":1,"customer_id":1,"trigger_type":"PURCHASE_COUNT","trigger_value":1,"trigger_threshold":1,"outputs":[]}}', status: 200)
    result = @client.reward_grants.get(reward_grant: 1)
    refute_nil result
  end

  # Parameterized authentication error tests (one per endpoint).
  [
    {name: :list, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/reward-grants(\?|\z)}},
    {name: :issue, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/reward-grants(\?|\z)}, args: {reward_rule_id: 1, customer_id: 1}},
    {name: :search, verb: :post, url: %r{\Ahttps://sell\.app/api/v2/reward-grants/search(\?|\z)}},
    {name: :get, verb: :get, url: %r{\Ahttps://sell\.app/api/v2/reward-grants/1(\?|\z)}, args: {reward_grant: 1}},
  ].each do |spec|
    define_method("test_#{spec[:name]}_raises_authentication_error_on_401") do
      stub_request(spec[:verb], spec[:url])
        .to_return(body: '{"message": "Unauthorized"}', status: 401)
      assert_raises(SellApp::AuthenticationError) do
        @client.reward_grants.public_send(spec[:name], **(spec[:args] || {}))
      end
    end
  end
end
