# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

require 'test_helper'

class CustomerPortalModelRoundTripTest < Minitest::Test
  def test_customer_portal_order_line_item_round_trip
    fixture = {
      "id" => 1,
      "product_id" => 1,
      "product_variant_id" => 1,
      "product_title" => 'stub',
      "variant_title" => 'stub',
      "quantity" => 1,
      "status" => 'stub',
    }
    model = SellApp::CustomerPortalOrderLineItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["product_id"], json[:product_id]
    assert_equal fixture["product_variant_id"], json[:product_variant_id]
    assert_equal fixture["product_title"], json[:product_title]
    assert_equal fixture["variant_title"], json[:variant_title]
    assert_equal fixture["quantity"], json[:quantity]
    assert_equal fixture["status"], json[:status]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_customer_portal_order_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "currency" => 'stub',
      "subtotal_cents" => 1,
      "total_cents" => 1,
      "line_items" => JSON.parse('[]'),
      "created_at" => '2024-01-01T00:00:00Z',
      "updated_at" => '2024-01-01T00:00:00Z',
    }
    model = SellApp::CustomerPortalOrder.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["currency"], json[:currency]
    assert_equal fixture["subtotal_cents"], json[:subtotal_cents]
    assert_equal fixture["total_cents"], json[:total_cents]
    assert_equal fixture["created_at"], json[:created_at]
    assert_equal fixture["updated_at"], json[:updated_at]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_customer_portal_profile_response_value_200_applicat_033e1c78cc821142_round_trip
    model = SellApp::GetCustomerPortalProfileResponseValue200ApplicationJsonPropertyDataPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_get_customer_portal_profile_response_value_200_applicat_b14d0da3c725d58c_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::GetCustomerPortalProfileResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_customer_portal_profile_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
    }
    model = SellApp::SdkGetCustomerPortalProfileResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_customer_portal_profile_request_application_json_b85c03d02098d545_round_trip
    model = SellApp::UpdateCustomerPortalProfileRequestApplicationJsonPropertyMetadataMapValue.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_update_customer_portal_profile_request_application_json_64ffb4ccea159997_round_trip
    model = SellApp::UpdateCustomerPortalProfileRequestApplicationJsonPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_sdk_update_customer_portal_profile_request_application_json_round_trip
    fixture = {
      "email" => 'sdk@example.com',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::SdkUpdateCustomerPortalProfileRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_customer_portal_profile_response_value_200_appli_0d05a9df88ca5004_round_trip
    model = SellApp::UpdateCustomerPortalProfileResponseValue200ApplicationJsonPropertyDataPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_update_customer_portal_profile_response_value_200_appli_f426cb31a5e240ec_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::UpdateCustomerPortalProfileResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_update_customer_portal_profile_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
    }
    model = SellApp::SdkUpdateCustomerPortalProfileResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_list_customer_portal_orders_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
      "links" => JSON.parse('{"first":"stub","last":"stub","prev":"stub","next":"stub"}'),
      "meta" => JSON.parse('{"current_page":1,"from":1,"last_page":1,"links":[],"path":"stub","per_page":1,"to":1,"total":1}'),
    }
    model = SellApp::SdkListCustomerPortalOrdersResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_customer_portal_order_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","currency":"stub","subtotal_cents":1,"total_cents":1,"line_items":[],"created_at":"2024-01-01T00:00:00Z","updated_at":"2024-01-01T00:00:00Z"}'),
    }
    model = SellApp::SdkGetCustomerPortalOrderResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_customer_portal_subscriptions_response_value_200_a_d516b72def2eabcf_round_trip
    model = SellApp::ListCustomerPortalSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_list_customer_portal_subscriptions_response_value_200_a_a0defe6d3d636f8c_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::ListCustomerPortalSubscriptionsResponseValue200ApplicationJsonPropertyDataItemPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_customer_portal_subscriptions_response_value_200_a_adf4e71e216ef14d_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::ListCustomerPortalSubscriptionsResponseValue200ApplicationJsonPropertyDataItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_list_customer_portal_subscriptions_response_value_2_b195e1339dee14ac_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
    }
    model = SellApp::SdkListCustomerPortalSubscriptionsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_customer_portal_subscription_response_value_200_app_7f60348c3cb26504_round_trip
    model = SellApp::GetCustomerPortalSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_get_customer_portal_subscription_response_value_200_app_c8294b0dbd34ac0a_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::GetCustomerPortalSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_customer_portal_subscription_response_value_200_app_de83e054e429757c_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::GetCustomerPortalSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_customer_portal_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkGetCustomerPortalSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_customer_portal_subscription_capabilities_response_08ac914b08743f57_round_trip
    fixture = {
      "available" => true,
      "reason" => 'stub',
    }
    model = SellApp::GetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyDataPropertyCapabilitiesMapValue.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["available"], json[:available]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_get_customer_portal_subscription_capabilities_response_cc943348bd4b60ec_round_trip
    model = SellApp::GetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyDataPropertyCapabilities.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_get_customer_portal_subscription_capabilities_response_813909143cbd1ea5_round_trip
    fixture = {
      "subscription_id" => 1,
      "capabilities" => JSON.parse('{}'),
    }
    model = SellApp::GetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["subscription_id"], json[:subscription_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_get_customer_portal_subscription_capabilities_respo_773caff55d8bb70c_round_trip
    fixture = {
      "data" => JSON.parse('{"subscription_id":1,"capabilities":{}}'),
    }
    model = SellApp::SdkGetCustomerPortalSubscriptionCapabilitiesResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_customer_portal_entitlements_response_value_200_ap_45cc6ca1c65d2d58_round_trip
    fixture = {
      "type" => 'stub',
      "id" => 1,
      "name" => 'stub',
    }
    model = SellApp::ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItemPropertySubject.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["type"], json[:type]
    assert_equal fixture["name"], json[:name]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_list_customer_portal_entitlements_response_value_200_ap_8594383f7d43db82_round_trip
    fixture = {
      "id" => 'item:1',
      "kind" => 'delivered_product',
      "state" => 'pending',
      "customer_id" => 1,
      "subject" => JSON.parse('{"type":"stub","id":1,"name":"stub"}'),
    }
    model = SellApp::ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItem.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["customer_id"], json[:customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_list_customer_portal_entitlements_response_value_20_5ae54a85a552acd7_round_trip
    fixture = {
      "data" => JSON.parse('[]'),
    }
    model = SellApp::SdkListCustomerPortalEntitlementsResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_customer_subscription_at_period_end_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkCancelCustomerSubscriptionAtPeriodEndRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_customer_subscription_at_period_end_response_val_e11ff4f0b23dea7a_round_trip
    model = SellApp::CancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_cancel_customer_subscription_at_period_end_response_val_400775a4a08b1f68_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::CancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_customer_subscription_at_period_end_response_val_1b237a9df5e2d312_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::CancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_customer_subscription_at_period_end_response_4d7d235d2245af41_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkCancelCustomerSubscriptionAtPeriodEndResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_customer_subscription_immediately_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkCancelCustomerSubscriptionImmediatelyRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_customer_subscription_immediately_response_value_26878c257b5af4e5_round_trip
    model = SellApp::CancelCustomerSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_cancel_customer_subscription_immediately_response_value_d762d4b5b0812a02_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::CancelCustomerSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_cancel_customer_subscription_immediately_response_value_4f922b4e84788fe6_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::CancelCustomerSubscriptionImmediatelyResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_cancel_customer_subscription_immediately_response_v_3cdcf09c81010590_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkCancelCustomerSubscriptionImmediatelyResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_pause_customer_subscription_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkPauseCustomerSubscriptionRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_pause_customer_subscription_response_value_200_applicat_8bf9c73dfe762f34_round_trip
    model = SellApp::PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_pause_customer_subscription_response_value_200_applicat_bd8916d023679e65_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_pause_customer_subscription_response_value_200_applicat_af208d6ddbfa995f_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::PauseCustomerSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_pause_customer_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkPauseCustomerSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_resume_customer_subscription_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkResumeCustomerSubscriptionRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_resume_customer_subscription_response_value_200_applica_33bbabda45d97f71_round_trip
    model = SellApp::ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_resume_customer_subscription_response_value_200_applica_c642495eb5e4db3a_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_resume_customer_subscription_response_value_200_applica_1d78041ee517c32a_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::ResumeCustomerSubscriptionResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_resume_customer_subscription_response_value_200_application_json_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkResumeCustomerSubscriptionResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_update_customer_subscription_payment_method_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkUpdateCustomerSubscriptionPaymentMethodRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_customer_subscription_payment_method_response_va_3990946206084a72_round_trip
    model = SellApp::UpdateCustomerSubscriptionPaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_update_customer_subscription_payment_method_response_va_b87e2f1eba01177d_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::UpdateCustomerSubscriptionPaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_update_customer_subscription_payment_method_response_va_9476695c7a3f9972_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::UpdateCustomerSubscriptionPaymentMethodResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_update_customer_subscription_payment_method_respons_e87ff28ee5c705ab_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkUpdateCustomerSubscriptionPaymentMethodResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_preview_customer_subscription_plan_change_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkPreviewCustomerSubscriptionPlanChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_customer_subscription_plan_change_response_valu_cbb420df88fca7dc_round_trip
    model = SellApp::PreviewCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_preview_customer_subscription_plan_change_response_valu_afd3ce7dc51846e6_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::PreviewCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_customer_subscription_plan_change_response_valu_292b713e27004f87_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::PreviewCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_preview_customer_subscription_plan_change_response_33f099059c9fe4e9_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkPreviewCustomerSubscriptionPlanChangeResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_confirm_customer_subscription_plan_change_request_application_json_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkConfirmCustomerSubscriptionPlanChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_customer_subscription_plan_change_response_valu_be2e9aa48dd8cdb5_round_trip
    model = SellApp::ConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_confirm_customer_subscription_plan_change_response_valu_8f18d8bd8f4f9b79_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::ConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_customer_subscription_plan_change_response_valu_61645c9ab28a4ddf_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::ConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_confirm_customer_subscription_plan_change_response_7b34bd27e3728a61_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkConfirmCustomerSubscriptionPlanChangeResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_preview_customer_subscription_renewal_date_change_r_1c87ad45642cd397_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkPreviewCustomerSubscriptionRenewalDateChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_customer_subscription_renewal_date_change_respo_75f3149dcc4d5fd1_round_trip
    model = SellApp::PreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_preview_customer_subscription_renewal_date_change_respo_f49367224934c0ce_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::PreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_preview_customer_subscription_renewal_date_change_respo_8bb4aa86f1b8a82c_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::PreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_preview_customer_subscription_renewal_date_change_r_cfac8f32a7fa71d1_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkPreviewCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_confirm_customer_subscription_renewal_date_change_r_1d60f8388ee9d4a0_round_trip
    fixture = {
      "preview_id" => 'stub',
      "product_variant_id" => 1,
      "renewal_date" => '2024-01-01',
      "return_url" => 'https://example.com',
      "reason" => 'stub',
    }
    model = SellApp::SdkConfirmCustomerSubscriptionRenewalDateChangeRequestApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_customer_subscription_renewal_date_change_respo_92ed1c9cbced40d4_round_trip
    model = SellApp::ConfirmCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomerPropertyMetadata.new('{}')
    json = model.to_h
    assert_kind_of Hash, json
  end

  def test_confirm_customer_subscription_renewal_date_change_respo_04eefb3f38acd135_round_trip
    fixture = {
      "id" => 1,
      "email" => 'sdk@example.com',
      "external_id" => 'stub',
      "name" => 'stub',
      "locale" => 'en',
      "metadata" => JSON.parse('{}'),
    }
    model = SellApp::ConfirmCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyDataPropertyCustomer.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["email"], json[:email]
    assert_equal fixture["external_id"], json[:external_id]
    assert_equal fixture["name"], json[:name]
    assert_equal fixture["locale"], json[:locale]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_confirm_customer_subscription_renewal_date_change_respo_999430742430048f_round_trip
    fixture = {
      "id" => 1,
      "status" => 'stub',
      "subscription_id" => 'stub',
      "customer_id" => 'stub',
      "provider_subscription_id" => 'stub',
      "provider_customer_id" => 'stub',
      "customer" => JSON.parse('{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}'),
      "product_variant_id" => 1,
    }
    model = SellApp::ConfirmCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJsonPropertyData.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    assert_equal fixture["id"], json[:id]
    assert_equal fixture["status"], json[:status]
    assert_equal fixture["provider_subscription_id"], json[:provider_subscription_id]
    assert_equal fixture["provider_customer_id"], json[:provider_customer_id]
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end

  def test_sdk_confirm_customer_subscription_renewal_date_change_r_854560ae195509dc_round_trip
    fixture = {
      "data" => JSON.parse('{"id":1,"status":"stub","provider_subscription_id":"stub","provider_customer_id":"stub","customer":{"id":1,"email":"sdk@example.com","external_id":"stub","name":"stub","locale":"en","metadata":{}}}'),
    }
    model = SellApp::SdkConfirmCustomerSubscriptionRenewalDateChangeResponseValue200ApplicationJson.new(fixture.to_json)
    json = model.to_h
    assert_kind_of Hash, json
    fixture.each_key { |k| assert json.key?(k.to_sym) || json.key?(k), "Expected to_h to include key #{k}" }
  end
end
