# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  BatchCreateSectionsResponseValue201ApplicationJsonPropertyDataItemPropertyProductsItem = BatchCreateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem
end
