# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateNotificationChannelRequestApplicationJsonPropertyChannelOneOfValue1 < SellApp::Types::BaseModel
    HASH_ATTRS = {
      type: :type,
      email: :email,
      allowed_notifications: :allowed_notifications
    }.freeze

    SCHEMA = {
      type: {required: true, schema: {kind: :literal, value: "email"}},
      email: {required: true, schema: {kind: :string, format: "email"}},
      allowed_notifications: {required: true, schema: {kind: :array, items: {kind: :string}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :type,
      :email,
      :allowed_notifications

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @type = hash[:type]
      @email = hash[:email]
      @allowed_notifications = hash[:allowed_notifications]
    end
  end
end
