# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyCustomerInformation < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      email: :email,
      country: :country,
      location: :location,
      ip: :ip,
      proxied: :proxied,
      browser_agent: :browser_agent,
      vat: :vat
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      email: {required: true, schema: {kind: :string}},
      country: {required: true, schema: {kind: :nullable, inner: {kind: :string}}},
      location: {required: true, schema: {kind: :string}},
      ip: {required: true, schema: {kind: :string}},
      proxied: {required: true, schema: {kind: :boolean}},
      browser_agent: {required: true, schema: {kind: :string}},
      vat: {required: true, schema: {kind: :nullable, inner: {kind: :model, name: "SellApp::CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyCustomerInformationPropertyVat"}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :email,
      :country,
      :location,
      :ip,
      :proxied,
      :browser_agent,
      :vat

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @email = hash[:email]
      @country = hash[:country]
      @location = hash[:location]
      @ip = hash[:ip]
      @proxied = hash[:proxied]
      @browser_agent = hash[:browser_agent]
      @vat = hash[:vat] ? SellApp::CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyCustomerInformationPropertyVat.new(hash[:vat]) : nil
    end
  end
end
