# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyStatus = CreateCheckoutSessionResponseValue200ApplicationJsonPropertyInvoicePropertyStatus
end
