# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class CursorExpiredErrorFallback < SellApp::Types::BaseModel
    HASH_ATTRS = {
      transport: :transport,
      url: :url
    }.freeze

    SCHEMA = {
      transport: {required: true, schema: {kind: :literal, value: "cursor_polling"}},
      url: {required: true, schema: {kind: :string, format: "uri"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :transport,
      :url

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @transport = hash[:transport]
      @url = hash[:url]
    end
  end
end
