# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListProductSAddOnsResponseValue200ApplicationJsonAnyOfValue2PropertyDataItemPropertyVariantsItem = CreateAddOnDraftResponseValue201ApplicationJsonPropertyDataPropertyVariantsItem
end
