# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  ListCreditsProductsResponseValue200ApplicationJsonAnyOfValue1PropertyDataItemPropertyDefaultVariantValuePropertyRateTiersItem = CreateCreditsProductRequestApplicationJsonPropertyRateTiersItem
end
