# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SearchAddOnsResponseValue200ApplicationJsonAnyOfValue1PropertyDataItem = CreateAddOnDraftResponseValue201ApplicationJsonPropertyData
end
