# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SearchCreditsProductsResponseValue200ApplicationJsonAnyOfValue1PropertyDataItemPropertyDefaultVariant = CreateCreditsProductResponseValue201ApplicationJsonPropertyDataPropertyDefaultVariant
end
