# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class DeactivateLicenseResponseValue200ApplicationJsonPropertyData < SellApp::Types::BaseModel
    HASH_ATTRS = {
      deactivated: :deactivated,
      instance_id: :instance_id
    }.freeze

    SCHEMA = {
      deactivated: {required: true, schema: {kind: :boolean}},
      instance_id: {required: true, schema: {kind: :string}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :deactivated,
      :instance_id

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @deactivated = hash[:deactivated]
      @instance_id = hash[:instance_id]
    end
  end
end
