# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings < SellApp::Types::BaseModel
    HASH_ATTRS = {
      faq: :faq,
      video_url: :video_url,
      redirect_url: :redirect_url,
      product_title: :product_title,
      product_description: :product_description
    }.freeze

    SCHEMA = {
      faq: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::ProductFaqItem"}}},
      video_url: {required: true, schema: {kind: :string}},
      redirect_url: {required: true, schema: {kind: :string}},
      product_title: {required: true, schema: {kind: :string}},
      product_description: {required: true, schema: {kind: :string}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :faq,
      :video_url,
      :redirect_url,
      :product_title,
      :product_description

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @faq = hash[:faq] ? hash[:faq].map { |item| item ? SellApp::ProductFaqItem.new(item) : nil } : nil
      @video_url = hash[:video_url]
      @redirect_url = hash[:redirect_url]
      @product_title = hash[:product_title]
      @product_description = hash[:product_description]
    end
  end
end
