# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  BatchDeleteProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem = BatchCreateProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem
end
