# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ReplaceProductRequestApplicationJsonPropertyAdditionalInformationItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      type: :type,
      required: :required,
      label: :label,
      key: :key,
      options: :options,
      placeholder: :placeholder,
      description: :description,
      variant: :variant,
      date_options: :date_options
    }.freeze

    SCHEMA = {
      type: {required: true, schema: {kind: :enum, values: ["text", "number", "email", "phone", "currency", "link", "textarea", "select", "radio", "checkbox-group", "pillbox", "checkbox", "switch", "date", "date-range", "hidden"]}},
      required: {required: true, schema: {kind: :boolean}},
      label: {required: true, schema: {kind: :string}},
      key: {required: false, schema: {kind: :string}},
      options: {required: false, schema: {kind: :array, items: {kind: :string}}},
      placeholder: {required: false, schema: {kind: :string}},
      description: {required: false, schema: {kind: :string}},
      variant: {required: false, schema: {kind: :string}},
      date_options: {required: false, schema: {kind: :model, name: "SellApp::ReplaceProductRequestApplicationJsonPropertyAdditionalInformationItemPropertyDateOptions"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :type,
      :required,
      :label,
      :key,
      :options,
      :placeholder,
      :description,
      :variant,
      :date_options

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @type = hash[:type]
      @required = hash[:required]
      @label = hash[:label]
      @key = hash[:key]
      @options = hash[:options]
      @placeholder = hash[:placeholder]
      @description = hash[:description]
      @variant = hash[:variant]
      @date_options = hash[:date_options] ? SellApp::ReplaceProductRequestApplicationJsonPropertyAdditionalInformationItemPropertyDateOptions.new(hash[:date_options]) : nil
    end
  end
end
