# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SdkReplaceProductResponseValue200ApplicationJson = SdkCreateProductResponseValue201ApplicationJson
end
