# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  DeleteCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemPropertyAttachmentsItem = CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyAttachmentsItem
end
