# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ReorderCourseLessonsResponseValue200ApplicationJsonPropertyDataPropertySectionsItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      id: :id,
      title: :title,
      description: :description,
      sort_order: :sort_order,
      lessons: :lessons,
      created_at: :created_at,
      updated_at: :updated_at
    }.freeze

    SCHEMA = {
      id: {required: true, schema: {kind: :integer}},
      title: {required: true, schema: {kind: :string}},
      description: {required: true, schema: {kind: :nullable, inner: {kind: :string}}},
      sort_order: {required: true, schema: {kind: :integer, minimum: 1}},
      lessons: {required: true, schema: {kind: :array, items: {kind: :model, name: "SellApp::ReorderCourseLessonsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItem"}}},
      created_at: {required: true, schema: {kind: :string, format: "date-time"}},
      updated_at: {required: true, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :id,
      :title,
      :description,
      :sort_order,
      :lessons,
      :created_at,
      :updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @id = hash[:id]
      @title = hash[:title]
      @description = hash[:description]
      @sort_order = hash[:sort_order]
      @lessons = hash[:lessons] ? hash[:lessons].map { |item| item ? SellApp::ReorderCourseLessonsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItem.new(item) : nil } : nil
      @created_at = hash[:created_at]
      @updated_at = hash[:updated_at]
    end
  end
end
