# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkCreateCourseLessonRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      title: :title,
      type: :type,
      content: :content,
      is_preview: :is_preview,
      is_published: :is_published,
      assignment: :assignment,
      questions: :questions,
      expected_updated_at: :expected_updated_at
    }.freeze

    SCHEMA = {
      title: {required: true, schema: {kind: :string, max: 255}},
      type: {required: true, schema: {kind: :enum, values: ["lecture", "video", "text", "quiz", "assignment"]}},
      content: {required: false, schema: {kind: :nullable, inner: {kind: :string}}},
      is_preview: {required: false, schema: {kind: :boolean}},
      is_published: {required: false, schema: {kind: :boolean}},
      assignment: {required: false, schema: {kind: :model, name: "SellApp::CreateCourseLessonRequestApplicationJsonPropertyAssignment"}},
      questions: {required: false, schema: {kind: :array, items: {kind: :model, name: "SellApp::CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem"}, max: 12}},
      expected_updated_at: {required: false, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :title,
      :type,
      :content,
      :is_preview,
      :is_published,
      :assignment,
      :questions,
      :expected_updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @title = hash[:title]
      @type = hash[:type]
      @content = hash[:content]
      @is_preview = hash[:is_preview]
      @is_published = hash[:is_published]
      @assignment = hash[:assignment] ? SellApp::CreateCourseLessonRequestApplicationJsonPropertyAssignment.new(hash[:assignment]) : nil
      @questions = hash[:questions] ? hash[:questions].map { |item| item ? SellApp::CreateCourseLessonRequestApplicationJsonPropertyQuestionsItem.new(item) : nil } : nil
      @expected_updated_at = hash[:expected_updated_at]
    end
  end
end
