# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class SdkReplaceCourseRequestApplicationJson < SellApp::Types::BaseModel
    HASH_ATTRS = {
      category: :category,
      level: :level,
      language: :language,
      subtitle: :subtitle,
      author: :author,
      subcategory: :subcategory,
      what_you_learn: :what_you_learn,
      requirements: :requirements,
      certificate_enabled: :certificate_enabled,
      access_type: :access_type,
      access_duration_days: :access_duration_days,
      enrollment_limit: :enrollment_limit,
      delivery_text: :delivery_text,
      visibility: :visibility,
      expected_updated_at: :expected_updated_at
    }.freeze

    SCHEMA = {
      category: {required: false, schema: {kind: :nullable, inner: {kind: :enum, values: ["development", "business", "marketing", "design", "finance", "it-software", "personal-development", "productivity", "other", "null"]}}},
      level: {required: false, schema: {kind: :enum, values: ["all_levels", "beginner", "intermediate", "advanced"]}},
      language: {required: false, schema: {kind: :string, max: 255}},
      subtitle: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 120}}},
      author: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 120}}},
      subcategory: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 255}}},
      what_you_learn: {required: false, schema: {kind: :array, items: {kind: :string, max: 255}, max: 50}},
      requirements: {required: false, schema: {kind: :array, items: {kind: :string, max: 255}, max: 50}},
      certificate_enabled: {required: false, schema: {kind: :boolean}},
      access_type: {required: false, schema: {kind: :enum, values: ["lifetime", "limited"]}},
      access_duration_days: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1, maximum: 3650}}},
      enrollment_limit: {required: false, schema: {kind: :nullable, inner: {kind: :integer, minimum: 1}}},
      delivery_text: {required: false, schema: {kind: :nullable, inner: {kind: :string, max: 65535}}},
      visibility: {required: false, schema: {kind: :enum, values: ["PUBLIC", "ON_HOLD", "HIDDEN", "PRIVATE"]}},
      expected_updated_at: {required: false, schema: {kind: :string, format: "date-time"}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :category,
      :level,
      :language,
      :subtitle,
      :author,
      :subcategory,
      :what_you_learn,
      :requirements,
      :certificate_enabled,
      :access_type,
      :access_duration_days,
      :enrollment_limit,
      :delivery_text,
      :visibility,
      :expected_updated_at

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @category = hash[:category]
      @level = hash[:level]
      @language = hash[:language]
      @subtitle = hash[:subtitle]
      @author = hash[:author]
      @subcategory = hash[:subcategory]
      @what_you_learn = hash[:what_you_learn]
      @requirements = hash[:requirements]
      @certificate_enabled = hash[:certificate_enabled]
      @access_type = hash[:access_type]
      @access_duration_days = hash[:access_duration_days]
      @enrollment_limit = hash[:enrollment_limit]
      @delivery_text = hash[:delivery_text]
      @visibility = hash[:visibility]
      @expected_updated_at = hash[:expected_updated_at]
    end
  end
end
