# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyModifiersItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      type: :type,
      key: :key,
      amount_cents: :amount_cents,
      attributes: :attributes
    }.freeze

    SCHEMA = {
      type: {required: true, schema: {kind: :string}},
      key: {required: false, schema: {kind: :string}},
      amount_cents: {required: false, schema: {kind: :integer}},
      attributes: {required: false, schema: {kind: :model, name: "SellApp::GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyModifiersItemPropertyAttributes"}}
    }.freeze
    ADDITIONAL_PROPERTIES = false
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :type,
      :key,
      :amount_cents,
      :attributes

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @type = hash[:type]
      @key = hash[:key]
      @amount_cents = hash[:amount_cents]
      @attributes = hash[:attributes] ? SellApp::GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyModifiersItemPropertyAttributes.new(hash[:attributes]) : nil
    end
  end
end
