# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyAmounts < SellApp::Types::BaseModel
    HASH_ATTRS = {
      unit_price: :unit_price,
      subtotal_cents: :subtotal_cents,
      credit_cents: :credit_cents,
      total_exclusive_cents: :total_exclusive_cents,
      total_exclusive_usd_cents: :total_exclusive_usd_cents,
      total_cents: :total_cents,
      total_usd_cents: :total_usd_cents,
      revenue_cents: :revenue_cents,
      revenue_usd_cents: :revenue_usd_cents,
      fee_cents: :fee_cents,
      fee_rate: :fee_rate
    }.freeze

    SCHEMA = {
      unit_price: {required: true, schema: {kind: :nullable, inner: {kind: :string}}},
      subtotal_cents: {required: true, schema: {kind: :nullable, inner: {kind: :integer}}},
      credit_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      total_exclusive_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      total_exclusive_usd_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      total_cents: {required: true, schema: {kind: :integer}},
      total_usd_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      revenue_cents: {required: true, schema: {kind: :nullable, inner: {kind: :integer}}},
      revenue_usd_cents: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}},
      fee_cents: {required: true, schema: {kind: :nullable, inner: {kind: :integer}}},
      fee_rate: {required: false, schema: {kind: :nullable, inner: {kind: :integer}}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :unit_price,
      :subtotal_cents,
      :credit_cents,
      :total_exclusive_cents,
      :total_exclusive_usd_cents,
      :total_cents,
      :total_usd_cents,
      :revenue_cents,
      :revenue_usd_cents,
      :fee_cents,
      :fee_rate

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @unit_price = hash[:unit_price]
      @subtotal_cents = hash[:subtotal_cents]
      @credit_cents = hash[:credit_cents]
      @total_exclusive_cents = hash[:total_exclusive_cents]
      @total_exclusive_usd_cents = hash[:total_exclusive_usd_cents]
      @total_cents = hash[:total_cents]
      @total_usd_cents = hash[:total_usd_cents]
      @revenue_cents = hash[:revenue_cents]
      @revenue_usd_cents = hash[:revenue_usd_cents]
      @fee_cents = hash[:fee_cents]
      @fee_rate = hash[:fee_rate]
    end
  end
end
