# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SearchOrderLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyReferral = GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyReferral
end
