# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItemPropertyTax = GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertyTax
end
