# frozen_string_literal: true

# This file is auto-generated by oagen. Do not edit.

module SellApp
  class ListWebhookEventTypesResponseValue200ApplicationJsonPropertyDataItem < SellApp::Types::BaseModel
    HASH_ATTRS = {
      type: :type,
      version: :version,
      description: :description
    }.freeze

    SCHEMA = {
      type: {required: true, schema: {kind: :string}},
      version: {required: true, schema: {kind: :integer}},
      description: {required: true, schema: {kind: :string}}
    }.freeze
    ADDITIONAL_PROPERTIES = true
    MODEL_CONSTRAINTS = {}.freeze

    attr_accessor \
      :type,
      :version,
      :description

    def initialize(json)
      hash = self.class.normalize(json)
      self.class.validate_schema!(hash, SCHEMA, direction: :response, additional_properties: ADDITIONAL_PROPERTIES, constraints: MODEL_CONSTRAINTS)
      @additional_properties = self.class.unknown_fields(hash, HASH_ATTRS.keys)
      @present_fields = hash.keys.map(&:to_s)
      @type = hash[:type]
      @version = hash[:version]
      @description = hash[:description]
    end
  end
end
